// Python Textual Bundle - Expr-Based Code Generation (Layer 4)
//
// Uses the panproto Expr layer for runtime code generation:
//   Config ──► Expr Evaluation ──► Generated Code

use std::collections::HashMap;
use std::path::PathBuf;
use crate::pipeline::expr_bundle::BundleConfig;

/// Generate all files for the Python Textual bundle using Expr-based generation
pub fn generate(_project_name: &str, spec_content: &str) -> HashMap<PathBuf, String> {
    use crate::pipeline::expr_bundle::{parse_spec_to_config, ExprBundleGenerator, ArtifactGenerator, BundleConfig};
    
    // Parse spec into config
    let mut config = parse_spec_to_config(spec_content);
    
    // Detect features from spec
    let has_counter = spec_content.to_lowercase().contains("counter");
    let has_todo = spec_content.to_lowercase().contains("todo");
    let has_hero = spec_content.to_lowercase().contains("hero");
    
    // Store features in config for generator access
    if has_counter {
        config.extra.insert("has_counter".to_string(), "true".to_string());
    }
    if has_todo {
        config.extra.insert("has_todo".to_string(), "true".to_string());
    }
    if has_hero {
        config.extra.insert("has_hero".to_string(), "true".to_string());
    }
    
    // Build Expr-based generator with spec-aware content
    ExprBundleGenerator::new("python-textual")
        .with_artifact("main.py", ArtifactGenerator::Expr(textual_main_py))
        .with_artifact("pyproject.toml", ArtifactGenerator::Expr(textual_pyproject_toml))
        .generate(&config)
}

fn textual_main_py(config: &BundleConfig) -> String {
    let has_counter = config.extra.get("has_counter").is_some();
    let has_todo = config.extra.get("has_todo").is_some();
    let has_hero = config.extra.get("has_hero").is_some();
    let project_name = &config.project_name;
    
    let mut imports = String::from("from textual.app import App, ComposeResult\n");
    imports.push_str("from textual.widgets import Header, Footer");
    
    if has_counter {
        imports.push_str(", Button, Static, Label");
    }
    if has_todo {
        imports.push_str(", Input, ListView, ListItem, Checkbox");
    }
    imports.push_str("\nfrom textual.containers import Container, Vertical, Horizontal\nfrom textual.reactive import reactive\n");
    
    let mut widgets = String::new();
    
    if has_counter {
        widgets.push_str(r##"

class CounterWidget(Static):
    """A simple counter widget."""
    count = reactive(0)
    
    def compose(self) -> ComposeResult:
        with Horizontal():
            yield Button("-", id="decrement", variant="error")
            yield Label("0", id="count-label")
            yield Button("+", id="increment", variant="success")
    
    def on_button_pressed(self, event: Button.Pressed) -> None:
        if event.button.id == "increment":
            self.count += 1
        elif event.button.id == "decrement":
            self.count -= 1
        self.query_one("#count-label", Label).update(str(self.count))
"##);
    }
    
    if has_todo {
        widgets.push_str(r##"

class TodoWidget(Static):
    """A todo list widget."""
    todos = reactive([])
    
    def compose(self) -> ComposeResult:
        yield Input(placeholder="Add a todo...", id="todo-input")
        yield ListView(id="todo-list")
    
    def on_input_submitted(self, event: Input.Submitted) -> None:
        if event.value:
            self.todos.append({"text": event.value, "done": False})
            self.query_one("#todo-list", ListView).append(ListItem(Checkbox(event.value)))
            self.query_one("#todo-input", Input).value = ""
"##);
    }
    
    if has_hero {
        widgets.push_str(r##"

class HeroWidget(Static):
    """A hero banner widget."""
    def compose(self) -> ComposeResult:
        with Container(classes="hero"):
            yield Label("Hello World!", id="hero-title")
            yield Label("Welcome to the app", id="hero-subtitle")
"##);
    }
    
    let pascal_name = to_pascal_case(project_name);
    
    let mut compose_body = String::new();
    if has_hero {
        compose_body.push_str("            yield HeroWidget()\n");
    }
    if has_counter {
        compose_body.push_str("            yield CounterWidget()\n");
    }
    if has_todo {
        compose_body.push_str("            yield TodoWidget()\n");
    }
    
    format!(r#"# phoenix: iu_id = "{}-app"
# Textual TUI app generated by Phoenix VCS

{}
{}
class {}App(App):
    """Main {} TUI application."""
    
    CSS = """
    Screen {{ align: center, middle; }}
    .hero {{ text-align: center; padding: 2; }}
    #hero-title {{ text-style: bold; color: $primary; text-size: 3; }}
    #hero-subtitle {{ color: $text-muted; }}
    """
    
    BINDINGS = [("q", "quit", "Quit")]
    
    def compose(self) -> ComposeResult:
        yield Header()
        with Container():
{}
        yield Footer()

if __name__ == "__main__":
    app = {}App()
    app.run()
"#, 
        project_name,
        imports,
        widgets,
        pascal_name,
        project_name,
        compose_body,
        pascal_name
    )
}

fn textual_pyproject_toml(config: &BundleConfig) -> String {
    format!(r#"[project]
name = "{}"
version = "{}"
description = "{}"
requires-python = ">=3.10"
dependencies = [
    "textual>=0.41.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "textual-dev>=1.0",
]
"#,
        config.project_name,
        config.version,
        config.project_description.as_deref().unwrap_or("Textual TUI app")
    )
}

fn to_pascal_case(s: &str) -> String {
    s.split(|c| c == '-' || c == '_')
        .map(|p| {
            let mut chars = p.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + &chars.as_str().to_lowercase(),
            }
        })
        .collect()
}
