// Python Textual Bundle - Native Rust Code Generation
// This file is loaded by the Phoenix VCS pipeline for isolated bundles

use std::collections::HashMap;
use std::path::PathBuf;

/// Generate all files for the Python Textual bundle
pub fn generate(project_name: &str, spec_content: &str) -> HashMap<PathBuf, String> {
    let mut files = HashMap::new();
    
    // Generate the main TUI app based on spec
    files.insert(PathBuf::from("src/main.py"), generate_main_py(project_name, spec_content));
    
    files
}

/// Generate main.py for Textual TUI app
fn generate_main_py(project_name: &str, spec_content: &str) -> String {
    // Parse spec to determine widgets
    let has_counter = spec_content.to_lowercase().contains("counter");
    let has_todo = spec_content.to_lowercase().contains("todo");
    let has_hero = spec_content.to_lowercase().contains("hero");
    
    let mut imports = String::from("from textual.app import App, ComposeResult\n");
    imports.push_str("from textual.widgets import Header, Footer");
    
    if has_counter {
        imports.push_str(", Button, Static, Label");
    }
    if has_todo {
        imports.push_str(", Input, ListView, ListItem, Checkbox");
    }
    imports.push_str("\nfrom textual.containers import Container, Vertical, Horizontal\n");
    
    let mut widgets = String::new();
    
    // Counter widget
    if has_counter {
        widgets.push_str(r##"

class CounterWidget(Static):
    """A simple counter widget."""
    
    count = reactive(0)
    
    def compose(self) -> ComposeResult:
        with Horizontal():
            yield Button("-", id="decrement", variant="error")
            yield Label("0", id="count-label")
            yield Button("+", id="increment", variant="success")
    
    def on_button_pressed(self, event: Button.Pressed) -> None:
        if event.button.id == "increment":
            self.count += 1
        elif event.button.id == "decrement":
            self.count -= 1
        self.query_one("#count-label", Label).update(str(self.count))
"##);
    }
    
    // Todo widget
    if has_todo {
        widgets.push_str(r##"

class TodoWidget(Static):
    """A todo list widget."""
    
    todos = reactive([])
    
    def compose(self) -> ComposeResult:
        yield Input(placeholder="Add a todo...", id="todo-input")
        yield ListView(id="todo-list")
    
    def on_input_submitted(self, event: Input.Submitted) -> None:
        if event.value:
            self.todos.append({"text": event.value, "done": False})
            self.query_one("#todo-list", ListView).append(ListItem(Checkbox(event.value)))
            self.query_one("#todo-input", Input).value = ""
"##);
    }
    
    // Hero widget
    if has_hero {
        widgets.push_str(r##"

class HeroWidget(Static):
    """A hero banner widget."""
    
    def compose(self) -> ComposeResult:
        with Container(classes="hero"):
            yield Label("Hello World!", id="hero-title")
            yield Label("Welcome to the app", id="hero-subtitle")
"##);
    }
    
    let app_class = format!(r##"

class {}App(App):
    """Main {} TUI application."""
    
    CSS = """
    Screen {{ align: center, middle; }}
    .hero {{ text-align: center; padding: 2; }}
    #hero-title {{ text-style: bold; color: $primary; text-size: 3; }}
    #hero-subtitle {{ color: $text-muted; }}
    """
    
    BINDINGS = [
        ("q", "quit", "Quit"),
        ("r", "refresh", "Refresh"),
    ]
    
    def compose(self) -> ComposeResult:
        yield Header()
        with Container():
"##, to_pascal_case(project_name), project_name);
    
    let mut compose_body = String::new();
    if has_hero {
        compose_body.push_str("            yield HeroWidget()\n");
    }
    if has_counter {
        compose_body.push_str("            yield CounterWidget()\n");
    }
    if has_todo {
        compose_body.push_str("            yield TodoWidget()\n");
    }
    
    format!(r#"# phoenix: iu_id = "{}-app"
# Textual TUI app generated by Phoenix VCS

{}
{}
{}
{}
        yield Footer()

if __name__ == "__main__":
    app = {}App()
    app.run()
"#, project_name, imports, widgets, app_class, compose_body, to_pascal_case(project_name))
}

/// Convert kebab-case/snake_case to PascalCase
fn to_pascal_case(s: &str) -> String {
    s.split(|c| c == '-' || c == '_')
        .map(|p| {
            let mut chars = p.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + &chars.as_str().to_lowercase(),
            }
        })
        .collect()
}
