import { Elena, html } from '@elenajs/core';

export class WelcomeCard extends Elena(HTMLElement) {
  static tagName = 'welcome-card';
  static props = ['title', 'message'];
  
  title = 'Welcome';
  message = 'Generated by Phoenix';
  
  render() {
    return html`
      <div style="background: linear-gradient(135deg, #667eea, #764ba2); padding: 2rem; border-radius: 1rem; color: white; text-align: center;">
        <h1>${this.title}</h1>
        <p>${this.message}</p>
      </div>
    `;
  }
}
