// phoenix: iu_id = "elena-app"
// Generated by Phoenix VCS for Elena Dashboard

// Note: ElenaJS is a fictional framework for demonstration.
// In a real implementation, this would use the actual ElenaJS API.
// For now, this uses standard Web Components with a similar API design.

// Welcome Component
class WelcomeCard extends HTMLElement {
  static get observedAttributes() {
    return ['title', 'message'];
  }

  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
  }

  connectedCallback() {
    this.render();
  }

  attributeChangedCallback() {
    this.render();
  }

  render() {
    const title = this.getAttribute('title') || 'Welcome';
    const message = this.getAttribute('message') || 'ElenaJS + Hono Fullstack App';
    
    this.shadowRoot!.innerHTML = `
      <style>
        :host {
          display: block;
          background: white;
          border-radius: 16px;
          padding: 32px;
          box-shadow: 0 10px 40px rgba(0,0,0,0.2);
          margin-bottom: 24px;
        }
        .welcome {
          text-align: center;
        }
        .welcome h1 {
          color: #764ba2;
          font-size: 2.5rem;
          margin: 0 0 16px 0;
        }
        .welcome p {
          color: #666;
          font-size: 1.25rem;
          margin: 0;
          line-height: 1.6;
        }
        .badge {
          display: inline-block;
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          padding: 8px 16px;
          border-radius: 20px;
          font-size: 0.875rem;
          font-weight: 600;
          margin-top: 16px;
        }
      </style>
      <div class="welcome">
        <h1>${title}</h1>
        <p>${message}</p>
        <span class="badge">ElenaJS + Hono</span>
      </div>
    `;
  }
}

// Todo List Component
class TodoList extends HTMLElement {
  private todos: Array<{id: number, text: string, completed: boolean}> = [];
  private newTodoText = '';

  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
  }

  connectedCallback() {
    this.loadTodos();
  }

  async loadTodos() {
    try {
      const res = await fetch('/api/todos');
      const data = await res.json();
      this.todos = data.todos;
      this.render();
    } catch (err) {
      console.error('Failed to load todos:', err);
    }
  }

  async addTodo() {
    if (!this.newTodoText.trim()) return;
    
    try {
      const res = await fetch('/api/todos', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: this.newTodoText.trim() })
      });
      
      if (res.ok) {
        const todo = await res.json();
        this.todos = [...this.todos, todo];
        this.newTodoText = '';
        this.render();
      }
    } catch (err) {
      console.error('Failed to add todo:', err);
    }
  }

  toggleTodo(id: number) {
    this.todos = this.todos.map(t =>
      t.id === id ? { ...t, completed: !t.completed } : t
    );
    this.render();
  }

  deleteTodo(id: number) {
    this.todos = this.todos.filter(t => t.id !== id);
    this.render();
  }

  render() {
    const remaining = this.todos.filter(t => !t.completed).length;
    
    this.shadowRoot!.innerHTML = `
      <style>
        :host {
          display: block;
          background: white;
          border-radius: 16px;
          padding: 24px;
          box-shadow: 0 4px 20px rgba(0,0,0,0.1);
          margin-bottom: 24px;
        }
        h2 {
          color: #333;
          margin: 0 0 20px 0;
          font-size: 1.5rem;
        }
        .input-row {
          display: flex;
          gap: 12px;
          margin-bottom: 20px;
        }
        input {
          flex: 1;
          padding: 12px 16px;
          border: 2px solid #e0e0e0;
          border-radius: 8px;
          font-size: 1rem;
          transition: border-color 0.2s;
        }
        input:focus {
          outline: none;
          border-color: #667eea;
        }
        button {
          padding: 12px 24px;
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          border: none;
          border-radius: 8px;
          font-size: 1rem;
          cursor: pointer;
          transition: transform 0.2s, box-shadow 0.2s;
        }
        button:hover {
          transform: translateY(-2px);
          box-shadow: 0 4px 12px rgba(102, 126, 234, 0.4);
        }
        ul {
          list-style: none;
          padding: 0;
          margin: 0;
        }
        li {
          display: flex;
          align-items: center;
          gap: 12px;
          padding: 12px 0;
          border-bottom: 1px solid #f0f0f0;
        }
        li:last-child {
          border-bottom: none;
        }
        input[type="checkbox"] {
          width: 20px;
          height: 20px;
          cursor: pointer;
        }
        span {
          flex: 1;
          font-size: 1rem;
        }
        span.completed {
          text-decoration: line-through;
          color: #999;
        }
        .delete-btn {
          background: #ff4757;
          padding: 8px 16px;
          font-size: 0.875rem;
        }
        .delete-btn:hover {
          box-shadow: 0 4px 12px rgba(255, 71, 87, 0.4);
        }
        .stats {
          margin-top: 16px;
          padding-top: 16px;
          border-top: 2px solid #f0f0f0;
          color: #666;
          font-size: 0.875rem;
        }
      </style>
      <h2>✨ Todo List</h2>
      <div class="input-row">
        <input 
          type="text" 
          id="todo-input"
          placeholder="What needs to be done?"
        />
        <button id="add-btn">Add</button>
      </div>
      <ul id="todo-list">
        ${this.todos.map(todo => `
          <li data-id="${todo.id}">
            <input 
              type="checkbox" 
              ${todo.completed ? 'checked' : ''}
            />
            <span class="${todo.completed ? 'completed' : ''}">${todo.text}</span>
            <button class="delete-btn">Delete</button>
          </li>
        `).join('')}
      </ul>
      <div class="stats">
        <strong>${remaining}</strong> of <strong>${this.todos.length}</strong> tasks remaining
      </div>
    `;

    // Add event listeners
    const input = this.shadowRoot!.getElementById('todo-input') as HTMLInputElement;
    const addBtn = this.shadowRoot!.getElementById('add-btn');
    const todoList = this.shadowRoot!.getElementById('todo-list');

    input?.addEventListener('input', (e) => {
      this.newTodoText = (e.target as HTMLInputElement).value;
    });

    input?.addEventListener('keypress', (e) => {
      if (e.key === 'Enter') this.addTodo();
    });

    addBtn?.addEventListener('click', () => this.addTodo());

    todoList?.querySelectorAll('li').forEach(li => {
      const id = Number(li.getAttribute('data-id'));
      const checkbox = li.querySelector('input[type="checkbox"]');
      const deleteBtn = li.querySelector('.delete-btn');

      checkbox?.addEventListener('change', () => this.toggleTodo(id));
      deleteBtn?.addEventListener('click', () => this.deleteTodo(id));
    });
  }
}

// User Card Component
class UserCard extends HTMLElement {
  static get observedAttributes() {
    return ['name', 'email'];
  }

  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
  }

  connectedCallback() {
    this.render();
  }

  attributeChangedCallback() {
    this.render();
  }

  render() {
    const name = this.getAttribute('name') || 'Demo User';
    const email = this.getAttribute('email') || 'demo@example.com';
    
    const initials = name
      .split(' ')
      .map(n => n[0])
      .join('')
      .toUpperCase()
      .slice(0, 2);

    this.shadowRoot!.innerHTML = `
      <style>
        :host {
          display: block;
          background: white;
          border-radius: 12px;
          padding: 20px;
          box-shadow: 0 4px 12px rgba(0,0,0,0.1);
          transition: transform 0.2s, box-shadow 0.2s;
        }
        :host(:hover) {
          transform: translateY(-4px);
          box-shadow: 0 8px 24px rgba(0,0,0,0.15);
        }
        .card {
          display: flex;
          align-items: center;
          gap: 16px;
        }
        .avatar {
          width: 56px;
          height: 56px;
          border-radius: 50%;
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          display: flex;
          align-items: center;
          justify-content: center;
          color: white;
          font-weight: 700;
          font-size: 1.25rem;
        }
        .info h3 {
          margin: 0;
          color: #333;
          font-size: 1.125rem;
        }
        .info p {
          margin: 4px 0 0 0;
          color: #666;
          font-size: 0.875rem;
        }
      </style>
      <div class="card">
        <div class="avatar">${initials}</div>
        <div class="info">
          <h3>${name}</h3>
          <p>${email}</p>
        </div>
      </div>
    `;
  }
}

// Main App Component
class ElenaApp extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
  }

  connectedCallback() {
    this.render();
  }

  render() {
    this.shadowRoot!.innerHTML = `
      <style>
        :host {
          display: block;
          max-width: 600px;
          margin: 40px auto;
        }
      </style>
      <welcome-card title="Elena Dashboard" message="Fullstack Web Components with Hono"></welcome-card>
      <todo-list></todo-list>
      <user-card name="Elena User" email="elena@example.com"></user-card>
    `;
  }
}

// Register all components
customElements.define('welcome-card', WelcomeCard);
customElements.define('todo-list', TodoList);
customElements.define('user-card', UserCard);
customElements.define('elena-app', ElenaApp);

console.log('🌸 Elena Dashboard loaded with Web Components + Hono');
