import { Elena, Component } from 'elenajs';

class WelcomeCard extends Component {
  render() {
    return `
      <div style="background: linear-gradient(135deg, #667eea, #764ba2); padding: 2rem; border-radius: 1rem; color: white; text-align: center;">
        <h1>${this.props.title || 'Welcome'}</h1>
        <p>${this.props.message || 'Generated by Phoenix'}</p>
      </div>
    `;
  }
}

class TodoList extends Component {
  constructor(props) {
    super(props);
    this.state = { todos: [], newTodo: '' };
  }
  
  async connectedCallback() {
    const res = await fetch('/api/todos');
    const data = await res.json();
    this.setState({ todos: data.todos });
  }
  
  render() {
    return `
      <div style="padding: 1rem;">
        <h2>Todo List</h2>
        <ul>
          ${this.state.todos.map(t => `<li>${t.text}</li>`).join('')}
        </ul>
      </div>
    `;
  }
}

class ElenaApp extends Component {
  render() {
    return `
      <div style="max-width: 800px; margin: 0 auto; padding: 1rem;">
        <welcome-card title="Elena Dashboard" message="Phoenix Generated"></welcome-card>
        <todo-list></todo-list>
      </div>
    `;
  }
}

customElements.define('welcome-card', WelcomeCard);
customElements.define('todo-list', TodoList);
customElements.define('elena-app', ElenaApp);

document.body.innerHTML = '<elena-app></elena-app>';
