import { Elena } from '@elenajs/core';

class WelcomeCard extends Elena(HTMLElement) {
  static tagName = 'welcome-card';
  static props = ['title', 'message'];
  
  title = 'Welcome';
  message = 'Generated by Phoenix';
  
  render() {
    return `
      <div style="background: linear-gradient(135deg, #667eea, #764ba2); padding: 2rem; border-radius: 1rem; color: white; text-align: center;">
        <h1>${this.title}</h1>
        <p>${this.message}</p>
      </div>
    `;
  }
}

class TodoList extends Elena(HTMLElement) {
  static tagName = 'todo-list';
  static props = [];
  
  todos = [];
  
  async connectedCallback() {
    super.connectedCallback();
    const res = await fetch('/api/todos');
    const data = await res.json();
    this.todos = data.todos;
    this.requestUpdate();
  }
  
  render() {
    return `
      <div style="padding: 1rem;">
        <h2>Todo List</h2>
        <ul>
          ${this.todos.map(t => `<li>${t.text}</li>`).join('')}
        </ul>
      </div>
    `;
  }
}

class ElenaApp extends Elena(HTMLElement) {
  static tagName = 'elena-app';
  static props = [];
  
  render() {
    return `
      <div style="max-width: 800px; margin: 0 auto; padding: 1rem;">
        <welcome-card title="Elena Dashboard" message="Phoenix Generated"></welcome-card>
        <todo-list></todo-list>
      </div>
    `;
  }
}

WelcomeCard.define();
TodoList.define();
ElenaApp.define();

document.body.appendChild(document.createElement('elena-app'));
