// Rust Bundle - Native Rust Code Generation
// This file is loaded by the Phoenix VCS pipeline for isolated bundles

use std::collections::HashMap;
use std::path::PathBuf;

/// Generate all files for the Rust bundle
pub fn generate(project_name: &str, _spec_content: &str) -> HashMap<PathBuf, String> {
    let mut files = HashMap::new();
    
    files.insert(PathBuf::from("Cargo.toml"), generate_cargo_toml(project_name));
    files.insert(PathBuf::from("src/main.rs"), generate_main_rs(project_name));
    
    files
}

/// Generate Cargo.toml for Rust app
fn generate_cargo_toml(project_name: &str) -> String {
    let sanitized = project_name.to_lowercase().replace(" ", "-").replace("_", "-");
    format!(r#"[package]
name = "{}"
version = "0.1.0"
edition = "2021"
authors = ["Phoenix VCS <phoenix@example.com>"]
description = "Rust application generated by Phoenix VCS"
license = "MIT"

[dependencies]
# Add your dependencies here

[profile.release]
opt-level = 3
lto = true
"#, sanitized)
}

/// Generate src/main.rs for Rust app
fn generate_main_rs(project_name: &str) -> String {
    format!(r#"// phoenix: iu_id = "{}-main"
// Rust application generated by Phoenix VCS

fn main() {{
    println!("🔥 {} starting...");
    
    // TODO: Add your application logic here
    println!("Hello from {}!");
}}
"#, project_name.to_lowercase().replace(" ", "-"), project_name, project_name)
}
