// phoenix: iu_id = "hono-api-server-api"
// Hono web API generated by Phoenix VCS

import { Hono } from 'hono';

const app = new Hono();

// Health check
app.get('/health', (c) => {
  return c.json({ 
    status: 'ok', 
    timestamp: new Date().toISOString(),
    service: 'hono-api-server'
  });
});

// Root
app.get('/', (c) => {
  return c.json({
    name: 'hono-api-server',
    version: '0.1.0',
    description: 'A fast, lightweight REST API server built with Hono and TypeScript. Designed for edge deployment with Bun runtime.'
  });
});

const port = parseInt(process.env.PORT || '3000');
console.log(`🔥 hono-api-server API server running on port ${port}`);

export default {
  port,
  fetch: app.fetch,
};
