// Python Flask Bundle - Expr-Based Code Generation (Layer 4)
//
// Uses the panproto Expr layer for runtime code generation:
//   Config ──► Expr Evaluation ──► Generated Code

use std::collections::HashMap;
use std::path::PathBuf;

/// Generate all files for the Python Flask bundle using Expr-based generation
pub fn generate(_project_name: &str, spec_content: &str) -> HashMap<PathBuf, String> {
    use crate::pipeline::expr_bundle::{parse_spec_to_config, ExprBundleGenerator, ArtifactGenerator};
    
    // Parse spec into config
    let config = parse_spec_to_config(spec_content);
    
    // Build Expr-based generator
    ExprBundleGenerator::new("python-flask")
        .with_artifact("app.py", ArtifactGenerator::Expr(flask_app_py))
        .with_artifact("pyproject.toml", ArtifactGenerator::Expr(flask_pyproject_toml))
        .generate(&config)
}

fn flask_app_py(config: &crate::pipeline::expr_bundle::BundleConfig) -> String {
    let id = config.project_name.replace("-", "_");
    let name = &config.project_name;
    let version = &config.version;
    let desc = config.project_description.as_deref().unwrap_or("Flask web API");
    
    format!(r##"# phoenix: iu_id = "{id}_app"
# Flask web API generated by Phoenix VCS

from flask import Flask, jsonify, request
from datetime import datetime
import os

app = Flask(__name__)

@app.route('/health', methods=['GET'])
def health_check():
    return jsonify({{
        'status': 'ok',
        'timestamp': datetime.now().isoformat(),
        'service': '{name}'
    }})

@app.route('/', methods=['GET'])
def index():
    return jsonify({{
        'name': '{name}',
        'version': '{version}',
        'description': '{desc}'
    }})

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    print(f'🔥 {name} server running on port {{port}}')
    app.run(host='0.0.0.0', port=port)
"##)
}

fn flask_pyproject_toml(config: &crate::pipeline::expr_bundle::BundleConfig) -> String {
    format!(r#"[project]
name = "{}"
version = "{}"
description = "{}"
requires-python = ">=3.10"
dependencies = [
    "flask>=2.3.0",
    "gunicorn>=21.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "black>=23.0",
    "flake8>=6.0",
]
"#,
        config.project_name,
        config.version,
        config.project_description.as_deref().unwrap_or("Flask web API")
    )
}
