// Python Flask Bundle - Native Rust Code Generation
// This file is loaded by the Phoenix VCS pipeline for isolated bundles

use std::collections::HashMap;
use std::path::PathBuf;

/// Generate all files for the Python Flask bundle
pub fn generate(project_name: &str, _spec_content: &str) -> HashMap<PathBuf, String> {
    let mut files = HashMap::new();
    
    files.insert(PathBuf::from("src/app.py"), generate_app_py(project_name));
    
    files
}

/// Generate app.py for Flask app
fn generate_app_py(project_name: &str) -> String {
    let sanitized = project_name.to_lowercase().replace(" ", "_").replace("-", "_");
    format!(r##"# phoenix: iu_id = "{}_app"
# Flask web API generated by Phoenix VCS

from flask import Flask, jsonify, request
from datetime import datetime
import os

app = Flask(__name__)

@app.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint."""
    return jsonify({{
        'status': 'ok',
        'timestamp': datetime.now().isoformat(),
        'service': '{}'
    }})

@app.route('/', methods=['GET'])
def index():
    """Root endpoint."""
    return jsonify({{
        'name': '{}',
        'version': '0.1.0',
        'description': 'Flask web API generated by Phoenix VCS'
    }})

@app.errorhandler(404)
def not_found(error):
    """Handle 404 errors."""
    return jsonify({{'error': 'Not found'}}), 404

@app.errorhandler(500)
def internal_error(error):
    """Handle 500 errors."""
    return jsonify({{'error': 'Internal server error'}}), 500

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    debug = os.environ.get('FLASK_DEBUG', 'false').lower() == 'true'
    print(f'🔥 {} API server running on port {{port}}')
    app.run(host='0.0.0.0', port=port, debug=debug)
"##, sanitized, project_name, project_name, project_name)
}
