//! ElenaJS Bundle Generator
//! 
//! Generates TypeScript web applications using ElenaJS framework with Hono backend

use std::collections::HashMap;

/// Generate ElenaJS + Hono application files
pub fn generate_elena_app(config: &serde_json::Value) -> Result<HashMap<String, String>, String> {
    let project_name = config.get("project_name")
        .and_then(|v| v.as_str())
        .unwrap_or("elena-app");
    
    let mut files = HashMap::new();
    
    // Generate package.json
    files.insert("package.json".to_string(), generate_package_json(project_name));
    
    // Generate tsconfig.json
    files.insert("tsconfig.json".to_string(), generate_tsconfig_json());
    
    // Generate vite.config.ts
    files.insert("vite.config.ts".to_string(), generate_vite_config());
    
    // Generate index.html
    files.insert("index.html".to_string(), generate_index_html(project_name));
    
    // Generate server.ts (Hono backend)
    files.insert("src/server.ts".to_string(), generate_server_ts(project_name));
    
    // Generate main.ts (client entry)
    files.insert("src/main.ts".to_string(), generate_main_ts(project_name));
    
    Ok(files)
}

fn generate_package_json(project_name: &str) -> String {
    format!(r#"{{
  "name": "{}",
  "version": "0.1.0",
  "description": "ElenaJS + Hono app generated by Phoenix VCS",
  "type": "module",
  "scripts": {{
    "dev": "concurrently \"bun run dev:server\" \"bun run dev:client\"",
    "dev:server": "bun run src/server.ts",
    "dev:client": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview",
    "start": "bun run dist/server.js"
  }},
  "dependencies": {{
    "elenajs": "^1.0.0",
    "hono": "^3.12.0",
    "@hono/node-server": "^1.8.0"
  }},
  "devDependencies": {{
    "@types/bun": "latest",
    "concurrently": "^8.2.0",
    "typescript": "^5.3.0",
    "vite": "^5.0.0"
  }}
}}"#, project_name)
}

fn generate_tsconfig_json() -> String {
    r#"{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "moduleResolution": "bundler",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "outDir": "./dist",
    "rootDir": "./src",
    "declaration": true,
    "sourceMap": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}"#.to_string()
}

fn generate_vite_config() -> String {
    r#"import { defineConfig } from 'vite';

export default defineConfig({
  server: {
    port: 5173,
    proxy: {
      '/api': 'http://localhost:3000'
    }
  },
  build: {
    outDir: 'dist/public',
    sourcemap: true
  }
});
"#.to_string()
}

fn generate_index_html(project_name: &str) -> String {
    format!(r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{} - ElenaJS App</title>
  <script type="module" src="/src/main.ts"></script>
  <style>
    * {{
      box-sizing: border-box;
    }}
    body {{
      margin: 0;
      padding: 20px;
      font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      min-height: 100vh;
    }}
  </style>
</head>
<body>
  <elena-app></elena-app>
</body>
</html>
"#, project_name)
}

fn generate_server_ts(project_name: &str) -> String {
    format!(r#"import {{ Hono }} from 'hono';
import {{ serve }} from '@hono/node-server';
import {{ logger }} from 'hono/logger';
import {{ cors }} from 'hono/cors';

const app = new Hono();

// Middleware
app.use('*', logger());
app.use('*', cors({{ origin: '*' }}));

// Health check
app.get('/api/health', (c) => {{
  return c.json({{ 
    status: 'ok', 
    service: '{}',
    timestamp: new Date().toISOString()
  }});
}});

// API routes
app.get('/api/users', (c) => {{
  return c.json({{
    users: [
      {{ id: 1, name: 'Alice', email: 'alice@example.com' }},
      {{ id: 2, name: 'Bob', email: 'bob@example.com' }},
      {{ id: 3, name: 'Carol', email: 'carol@example.com' }}
    ]
  }});
}});

app.get('/api/todos', (c) => {{
  return c.json({{
    todos: [
      {{ id: 1, text: 'Learn ElenaJS', completed: true }},
      {{ id: 2, text: 'Build web components', completed: false }},
      {{ id: 3, text: 'Deploy with Hono', completed: false }}
    ]
  }});
}});

app.post('/api/todos', async (c) => {{
  const body = await c.req.json();
  return c.json({{ 
    id: Date.now(),
    text: body.text,
    completed: false,
    created: true 
  }}, 201);
}});

// Serve static files in production
app.get('*', (c) => {{
  return c.html(`
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{}</title>
  <script type="module" src="/main.js"></script>
</head>
<body>
  <elena-app></elena-app>
</body>
</html>
  `);
}});

const port = process.env.PORT || 3000;

serve({{
  fetch: app.fetch,
  port: Number(port)
}}, (info) => {{
  console.log(`🚀 {} server running at http://localhost:${{info.port}}`);
}});
"#, project_name, project_name, project_name)
}

fn generate_main_ts(_project_name: &str) -> String {
    r#"// phoenix: iu_id = "elena-app"
// Generated by Phoenix VCS for ElenaJS + Hono

import { Component } from 'elenajs';

// Welcome Component
export class WelcomeCard extends Component {
  static get componentName() {
    return 'welcome-card';
  }

  static get properties() {
    return {
      title: { type: String, default: 'Welcome' },
      message: { type: String, default: 'ElenaJS + Hono Fullstack App' }
    };
  }

  render() {
    return `
      <style>
        :host {
          display: block;
          background: white;
          border-radius: 16px;
          padding: 32px;
          box-shadow: 0 10px 40px rgba(0,0,0,0.2);
          margin-bottom: 24px;
        }
        .welcome {
          text-align: center;
        }
        .welcome h1 {
          color: #764ba2;
          font-size: 2.5rem;
          margin: 0 0 16px 0;
        }
        .welcome p {
          color: #666;
          font-size: 1.25rem;
          margin: 0;
          line-height: 1.6;
        }
        .badge {
          display: inline-block;
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          padding: 8px 16px;
          border-radius: 20px;
          font-size: 0.875rem;
          font-weight: 600;
          margin-top: 16px;
        }
      </style>
      <div class="welcome">
        <h1>${this.title}</h1>
        <p>${this.message}</p>
        <span class="badge">ElenaJS + Hono</span>
      </div>
    `;
  }
}

// Todo List Component
export class TodoList extends Component {
  static get componentName() {
    return 'todo-list';
  }

  static get properties() {
    return {
      todos: { type: Array, default: [] },
      newTodo: { type: String, default: '' }
    };
  }

  connectedCallback() {
    super.connectedCallback();
    this.loadTodos();
  }

  async loadTodos() {
    try {
      const res = await fetch('/api/todos');
      const data = await res.json();
      this.todos = data.todos;
    } catch (err) {
      console.error('Failed to load todos:', err);
    }
  }

  async addTodo() {
    if (!this.newTodo.trim()) return;
    
    try {
      const res = await fetch('/api/todos', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: this.newTodo.trim() })
      });
      
      if (res.ok) {
        const todo = await res.json();
        this.todos = [...this.todos, todo];
        this.newTodo = '';
      }
    } catch (err) {
      console.error('Failed to add todo:', err);
    }
  }

  toggleTodo(id) {
    this.todos = this.todos.map(t =>
      t.id === id ? { ...t, completed: !t.completed } : t
    );
  }

  deleteTodo(id) {
    this.todos = this.todos.filter(t => t.id !== id);
  }

  handleInput(e) {
    this.newTodo = e.target.value;
  }

  handleKeyPress(e) {
    if (e.key === 'Enter') {
      this.addTodo();
    }
  }

  render() {
    const remaining = this.todos.filter(t => !t.completed).length;
    
    return `
      <style>
        :host {
          display: block;
          background: white;
          border-radius: 16px;
          padding: 24px;
          box-shadow: 0 4px 20px rgba(0,0,0,0.1);
          margin-bottom: 24px;
        }
        h2 {
          color: #333;
          margin: 0 0 20px 0;
          font-size: 1.5rem;
        }
        .input-row {
          display: flex;
          gap: 12px;
          margin-bottom: 20px;
        }
        input {
          flex: 1;
          padding: 12px 16px;
          border: 2px solid #e0e0e0;
          border-radius: 8px;
          font-size: 1rem;
          transition: border-color 0.2s;
        }
        input:focus {
          outline: none;
          border-color: #667eea;
        }
        button {
          padding: 12px 24px;
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          border: none;
          border-radius: 8px;
          font-size: 1rem;
          cursor: pointer;
          transition: transform 0.2s, box-shadow 0.2s;
        }
        button:hover {
          transform: translateY(-2px);
          box-shadow: 0 4px 12px rgba(102, 126, 234, 0.4);
        }
        ul {
          list-style: none;
          padding: 0;
          margin: 0;
        }
        li {
          display: flex;
          align-items: center;
          gap: 12px;
          padding: 12px 0;
          border-bottom: 1px solid #f0f0f0;
        }
        li:last-child {
          border-bottom: none;
        }
        input[type="checkbox"] {
          width: 20px;
          height: 20px;
          cursor: pointer;
        }
        span {
          flex: 1;
          font-size: 1rem;
        }
        span.completed {
          text-decoration: line-through;
          color: #999;
        }
        .delete-btn {
          background: #ff4757;
          padding: 8px 16px;
          font-size: 0.875rem;
        }
        .delete-btn:hover {
          box-shadow: 0 4px 12px rgba(255, 71, 87, 0.4);
        }
        .stats {
          margin-top: 16px;
          padding-top: 16px;
          border-top: 2px solid #f0f0f0;
          color: #666;
          font-size: 0.875rem;
        }
      </style>
      <h2>✨ Todo List</h2>
      <div class="input-row">
        <input 
          type="text" 
          .value="${this.newTodo}" 
          @input="${this.handleInput}" 
          @keypress="${this.handleKeyPress}"
          placeholder="What needs to be done?"
        />
        <button @click="${this.addTodo}">Add</button>
      </div>
      <ul>
        ${this.todos.map(todo => `
          <li>
            <input 
              type="checkbox" 
              .checked="${todo.completed}" 
              @change="${() => this.toggleTodo(todo.id)}"
            />
            <span class="${todo.completed ? 'completed' : ''}">${todo.text}</span>
            <button class="delete-btn" @click="${() => this.deleteTodo(todo.id)}">Delete</button>
          </li>
        `).join('')}
      </ul>
      <div class="stats">
        <strong>${remaining}</strong> of <strong>${this.todos.length}</strong> tasks remaining
      </div>
    `;
  }
}

// User Card Component
export class UserCard extends Component {
  static get componentName() {
    return 'user-card';
  }

  static get properties() {
    return {
      name: { type: String, default: 'Demo User' },
      email: { type: String, default: 'demo@example.com' }
    };
  }

  render() {
    const initials = this.name
      .split(' ')
      .map(n => n[0])
      .join('')
      .toUpperCase()
      .slice(0, 2);

    return `
      <style>
        :host {
          display: block;
          background: white;
          border-radius: 12px;
          padding: 20px;
          box-shadow: 0 4px 12px rgba(0,0,0,0.1);
          transition: transform 0.2s, box-shadow 0.2s;
        }
        :host(:hover) {
          transform: translateY(-4px);
          box-shadow: 0 8px 24px rgba(0,0,0,0.15);
        }
        .card {
          display: flex;
          align-items: center;
          gap: 16px;
        }
        .avatar {
          width: 56px;
          height: 56px;
          border-radius: 50%;
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          display: flex;
          align-items: center;
          justify-content: center;
          color: white;
          font-weight: 700;
          font-size: 1.25rem;
        }
        .info h3 {
          margin: 0;
          color: #333;
          font-size: 1.125rem;
        }
        .info p {
          margin: 4px 0 0 0;
          color: #666;
          font-size: 0.875rem;
        }
      </style>
      <div class="card">
        <div class="avatar">${initials}</div>
        <div class="info">
          <h3>${this.name}</h3>
          <p>${this.email}</p>
        </div>
      </div>
    `;
  }
}

// Register all components
if (typeof customElements !== 'undefined') {
  customElements.define(WelcomeCard.componentName, WelcomeCard);
  customElements.define(TodoList.componentName, TodoList);
  customElements.define(UserCard.componentName, UserCard);
}

// Main App Component
export class ElenaApp extends Component {
  static get componentName() {
    return 'elena-app';
  }

  render() {
    return `
      <style>
        :host {
          display: block;
          max-width: 600px;
          margin: 40px auto;
        }
      </style>
      <welcome-card></welcome-card>
      <todo-list></todo-list>
      <user-card></user-card>
    `;
  }
}

// Register app
if (typeof customElements !== 'undefined') {
  customElements.define(ElenaApp.componentName, ElenaApp);
}

console.log('🌸 ElenaJS + Hono app loaded');
"#.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_generate_elena_app() {
        let config = json!({
            "project_name": "test-elena-app"
        });
        
        let files = generate_elena_app(&config).unwrap();
        
        assert!(files.contains_key("package.json"));
        assert!(files.contains_key("src/main.ts"));
        assert!(files.contains_key("src/server.ts"));
        
        let main_ts = files.get("src/main.ts").unwrap();
        assert!(main_ts.contains("elenajs"));
        assert!(main_ts.contains("hono"));
    }
}
