/**
 * Architecture Target: sqlite-web-api
 *
 * A lightweight REST API backed by SQLite.
 * Stack: Hono (HTTP) + better-sqlite3 (DB) + Zod (validation)
 */

import type { Architecture } from '../models/architecture.js';

// ─── Shared files (written once, not generated by LLM) ─────────────────────

const DB_FILE = `import Database from 'better-sqlite3';
import { existsSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const DB_PATH = process.env.DB_PATH ?? 'data/app.db';

// Ensure directory exists
const dir = dirname(DB_PATH);
if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

const db = new Database(DB_PATH);

// Enable WAL mode for better concurrent read performance
db.pragma('journal_mode = WAL');
db.pragma('foreign_keys = ON');

/**
 * Run migrations. Each migration is idempotent (CREATE TABLE IF NOT EXISTS).
 * Modules register their migrations at import time.
 */
const migrations: Array<{ name: string; sql: string }> = [];

export function registerMigration(name: string, sql: string): void {
  migrations.push({ name, sql });
}

export function runMigrations(): void {
  for (const m of migrations) {
    db.exec(m.sql);
  }
}

export { db };
export type { Database };
`;

const APP_FILE = `import { Hono } from 'hono';
import { logger } from 'hono/logger';
import { cors } from 'hono/cors';

const app = new Hono();

app.use('*', logger());
app.use('*', cors());

app.get('/health', (c) => c.json({ status: 'ok', uptime: process.uptime() }));

/**
 * Mount a route module. Call this for each generated module.
 */
export function mount(path: string, router: Hono): void {
  app.route(path, router);
}

export { app };
`;

const SERVER_FILE = `import { serve } from '@hono/node-server';
import { app } from './app.js';
import { runMigrations } from './db.js';

// Import generated route modules (populated by scaffold)
// __ROUTE_IMPORTS__

const port = parseInt(process.env.PORT ?? '3000', 10);

// Run database migrations before starting
runMigrations();

console.log(\`Server running at http://localhost:\${port}\`);
serve({ fetch: app.fetch, port });
`;

// ─── LLM prompt extension ───────────────────────────────────────────────────

const SYSTEM_PROMPT_EXTENSION = `
## Architecture: sqlite-web-api

You are generating a route handler module for a Hono REST API backed by SQLite.

### CRITICAL import rules — follow EXACTLY, no exceptions

Your file MUST start with these EXACT three import lines:
\`\`\`
import { Hono } from 'hono';
import { db, registerMigration } from '../../db.js';
import { z } from 'zod';
\`\`\`

### FORBIDDEN — these will cause the build to fail
- FORBIDDEN: \`import Database from 'better-sqlite3'\` — NEVER import better-sqlite3 directly
- FORBIDDEN: \`new Database(...)\` — NEVER create a database instance
- FORBIDDEN: \`const db = ...\` — the db variable comes from the import above
- Use ONLY the \`db\` import from \`../../db.js\` for ALL database operations

### Module structure
- Export a Hono router instance as the DEFAULT export: \`export default router;\`
- Register your table schema via \`registerMigration('tablename', 'CREATE TABLE IF NOT EXISTS ...')\` at module scope.
- Include ALL CRUD routes for the resource in a single module (GET list, GET by id, POST create, PATCH update, DELETE).
- Use better-sqlite3 synchronous API: db.prepare(sql).run(), .get(), .all()
- Use parameterized queries ALWAYS — never interpolate user input into SQL.
- Parse request bodies with \`await c.req.json()\` and validate with Zod .safeParse().

### Response conventions
- 200 for successful reads
- 201 for successful creates (return the created resource)
- 204 for successful deletes (return c.body(null, 204))
- 400 for validation errors: \`{ error: "message" }\`
- 404 for not found: \`{ error: "Not found" }\`

### Data model
- Use integer primary keys with AUTOINCREMENT.
- Include a \`completed\` boolean column (as INTEGER 0/1) for task/todo resources when the spec mentions it.
- Include \`created_at TEXT NOT NULL DEFAULT (datetime('now'))\` for timestamps.
`;

const CODE_EXAMPLES = `
## Architecture Pattern Examples

### Example 1: CRUD route module for a "notes" resource

\`\`\`typescript
import { Hono } from 'hono';
import { z } from 'zod';
import { db, registerMigration } from '../../db.js';

// Register table migration
registerMigration('notes', \`
  CREATE TABLE IF NOT EXISTS notes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    body TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  )
\`);

const CreateNoteSchema = z.object({
  title: z.string().min(1).max(200),
  body: z.string().optional().default(''),
});

const UpdateNoteSchema = z.object({
  title: z.string().min(1).max(200).optional(),
  body: z.string().optional(),
});

const router = new Hono();

// List all notes
router.get('/', (c) => {
  const notes = db.prepare('SELECT * FROM notes ORDER BY created_at DESC').all();
  return c.json(notes);
});

// Get single note
router.get('/:id', (c) => {
  const note = db.prepare('SELECT * FROM notes WHERE id = ?').get(c.req.param('id'));
  if (!note) return c.json({ error: 'Note not found' }, 404);
  return c.json(note);
});

// Create note
router.post('/', async (c) => {
  const result = CreateNoteSchema.safeParse(await c.req.json());
  if (!result.success) return c.json({ error: result.error.issues[0].message }, 400);
  const { title, body } = result.data;
  const info = db.prepare('INSERT INTO notes (title, body) VALUES (?, ?)').run(title, body);
  const note = db.prepare('SELECT * FROM notes WHERE id = ?').get(info.lastInsertRowid);
  return c.json(note, 201);
});

// Update note
router.patch('/:id', async (c) => {
  const id = c.req.param('id');
  const existing = db.prepare('SELECT * FROM notes WHERE id = ?').get(id);
  if (!existing) return c.json({ error: 'Note not found' }, 404);
  const result = UpdateNoteSchema.safeParse(await c.req.json());
  if (!result.success) return c.json({ error: result.error.issues[0].message }, 400);
  const updates = result.data;
  if (updates.title !== undefined) db.prepare('UPDATE notes SET title = ? WHERE id = ?').run(updates.title, id);
  if (updates.body !== undefined) db.prepare('UPDATE notes SET body = ? WHERE id = ?').run(updates.body, id);
  const updated = db.prepare('SELECT * FROM notes WHERE id = ?').get(id);
  return c.json(updated);
});

// Delete note
router.delete('/:id', (c) => {
  const id = c.req.param('id');
  const existing = db.prepare('SELECT * FROM notes WHERE id = ?').get(id);
  if (!existing) return c.json({ error: 'Note not found' }, 404);
  db.prepare('DELETE FROM notes WHERE id = ?').run(id);
  return c.body(null, 204);
});

export default router;

export const _phoenix = {
  iu_id: 'example',
  name: 'Notes',
  risk_tier: 'medium',
  canon_ids: [],
} as const;
\`\`\`

### Example 2: Resource with foreign keys, JOINs, filtering, and cascade protection

\`\`\`typescript
import { Hono } from 'hono';
import { db, registerMigration } from '../../db.js';
import { z } from 'zod';

// Register migrations for BOTH tables this module touches
registerMigration('projects', \`
  CREATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  )
\`);

registerMigration('tasks', \`
  CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    done INTEGER NOT NULL DEFAULT 0,
    project_id INTEGER REFERENCES projects(id),
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  )
\`);

const CreateTaskSchema = z.object({
  title: z.string().min(1).max(200),
  project_id: z.number().int().optional(),
});

const UpdateTaskSchema = z.object({
  title: z.string().min(1).max(200).optional(),
  done: z.number().int().min(0).max(1).optional(),
  project_id: z.number().int().nullable().optional(),
});

const router = new Hono();

// List with LEFT JOIN and optional query filters
router.get('/', (c) => {
  let sql = 'SELECT tasks.*, projects.name as project_name FROM tasks LEFT JOIN projects ON tasks.project_id = projects.id';
  const conditions: string[] = [];
  const params: unknown[] = [];

  const done = c.req.query('done');
  if (done !== undefined) { conditions.push('tasks.done = ?'); params.push(Number(done)); }

  const projectId = c.req.query('project_id');
  if (projectId !== undefined) { conditions.push('tasks.project_id = ?'); params.push(Number(projectId)); }

  if (conditions.length > 0) sql += ' WHERE ' + conditions.join(' AND ');
  sql += ' ORDER BY tasks.created_at DESC';

  return c.json(db.prepare(sql).all(...params));
});

// Get single with JOIN
router.get('/:id', (c) => {
  const row = db.prepare('SELECT tasks.*, projects.name as project_name FROM tasks LEFT JOIN projects ON tasks.project_id = projects.id WHERE tasks.id = ?').get(c.req.param('id'));
  if (!row) return c.json({ error: 'Not found' }, 404);
  return c.json(row);
});

// Create with FK validation
router.post('/', async (c) => {
  let body; try { body = await c.req.json(); } catch { return c.json({ error: 'Invalid JSON' }, 400); }
  const result = CreateTaskSchema.safeParse(body);
  if (!result.success) return c.json({ error: result.error.issues[0].message }, 400);
  const { title, project_id } = result.data;
  if (project_id !== undefined) {
    const proj = db.prepare('SELECT id FROM projects WHERE id = ?').get(project_id);
    if (!proj) return c.json({ error: 'Project not found' }, 400);
  }
  const info = db.prepare('INSERT INTO tasks (title, project_id) VALUES (?, ?)').run(title, project_id ?? null);
  const task = db.prepare('SELECT tasks.*, projects.name as project_name FROM tasks LEFT JOIN projects ON tasks.project_id = projects.id WHERE tasks.id = ?').get(info.lastInsertRowid);
  return c.json(task, 201);
});

// Update
router.patch('/:id', async (c) => {
  const id = c.req.param('id');
  if (!db.prepare('SELECT id FROM todos WHERE id = ?').get(id)) return c.json({ error: 'Not found' }, 404);
  let body; try { body = await c.req.json(); } catch { return c.json({ error: 'Invalid JSON' }, 400); }
  const result = UpdateTaskSchema.safeParse(body);
  if (!result.success) return c.json({ error: result.error.issues[0].message }, 400);
  const u = result.data;
  if (u.title !== undefined) db.prepare('UPDATE tasks SET title = ? WHERE id = ?').run(u.title, id);
  if (u.done !== undefined) db.prepare('UPDATE tasks SET done = ? WHERE id = ?').run(u.done, id);
  if (u.project_id !== undefined) db.prepare('UPDATE tasks SET project_id = ? WHERE id = ?').run(u.project_id, id);
  return c.json(db.prepare('SELECT tasks.*, projects.name as project_name FROM tasks LEFT JOIN projects ON tasks.project_id = projects.id WHERE tasks.id = ?').get(id));
});

// Delete
router.delete('/:id', (c) => {
  const id = c.req.param('id');
  if (!db.prepare('SELECT id FROM tasks WHERE id = ?').get(id)) return c.json({ error: 'Not found' }, 404);
  db.prepare('DELETE FROM tasks WHERE id = ?').run(id);
  return c.body(null, 204);
});

export default router;
export const _phoenix = { iu_id: 'example2', name: 'Tasks', risk_tier: 'medium', canon_ids: [] } as const;
\`\`\`

### Key patterns:
1. \`import { db, registerMigration } from '../../db.js'\` — ALWAYS use this exact import
2. registerMigration() for ALL tables the module touches, including referenced tables
3. LEFT JOIN to include related resource names (e.g., category_name, project_name)
4. Query parameter filtering with dynamic WHERE clause building
5. Foreign key validation: check referenced row exists before INSERT
6. Cascade protection: check for dependent rows before DELETE of parent resource
7. Zod schemas for create/update validation
8. Return the created/updated resource with JOINed data after mutation
9. Export default router + export _phoenix metadata
`;

// ─── Architecture definition ────────────────────────────────────────────────

export const sqliteWebApi: Architecture = {
  name: 'sqlite-web-api',
  description: 'REST API backed by SQLite — Hono + better-sqlite3 + Zod',
  runtime: 'node',

  packages: {
    'hono': '^4.6.0',
    '@hono/node-server': '^1.13.0',
    'better-sqlite3': '^11.7.0',
    'zod': '^3.24.0',
  },

  devPackages: {
    'typescript': '^5.4.0',
    'vitest': '^2.0.0',
    '@types/node': '^22.0.0',
    '@types/better-sqlite3': '^7.6.0',
    'tsx': '^4.0.0',
  },

  systemPromptExtension: SYSTEM_PROMPT_EXTENSION,
  codeExamples: CODE_EXAMPLES,

  sharedFiles: {
    'src/db.ts': DB_FILE,
    'src/app.ts': APP_FILE,
  },

  packageJsonExtras: {
    scripts: {
      dev: 'tsx watch src/server.ts',
      start: 'tsx src/server.ts',
      build: 'tsc',
      test: 'vitest run',
    },
  },
};
