// Node.js Express Bundle - Native Rust Code Generation
// This file is loaded by the Phoenix VCS pipeline for isolated bundles

use std::collections::HashMap;
use std::path::PathBuf;

/// Generate all files for the Node.js Express bundle
pub fn generate(project_name: &str, _spec_content: &str) -> HashMap<PathBuf, String> {
    let mut files = HashMap::new();
    
    files.insert(PathBuf::from("package.json"), generate_package_json(project_name));
    files.insert(PathBuf::from("app.js"), generate_app_js(project_name));
    files.insert(PathBuf::from(".env.example"), generate_env_example(project_name));
    
    files
}

/// Generate package.json for Express app
fn generate_package_json(project_name: &str) -> String {
    let sanitized = project_name.to_lowercase().replace(" ", "-").replace("_", "-");
    format!(r#"{{
  "name": "{}",
  "version": "0.1.0",
  "description": "Express web API generated by Phoenix VCS",
  "main": "app.js",
  "scripts": {{
    "start": "node app.js",
    "dev": "nodemon app.js",
    "test": "jest"
  }},
  "dependencies": {{
    "express": "^4.18.0",
    "mongoose": "^7.0.0",
    "cors": "^2.8.5",
    "helmet": "^7.0.0",
    "morgan": "^1.10.0",
    "dotenv": "^16.0.0"
  }},
  "devDependencies": {{
    "nodemon": "^3.0.0",
    "jest": "^29.0.0"
  }},
  "engines": {{
    "node": ">=18.0.0"
  }}
}}"#, sanitized)
}

/// Generate app.js for Express app
fn generate_app_js(project_name: &str) -> String {
    format!(r#"// phoenix: iu_id = "{}-app"
// Express web API generated by Phoenix VCS

const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(helmet());
app.use(cors());
app.use(morgan('dev'));
app.use(express.json());
app.use(express.urlencoded({{ extended: true }}));

// Health check endpoint
app.get('/health', (req, res) => {{
  res.json({{ status: 'ok', timestamp: new Date().toISOString() }});
}});

// Root endpoint
app.get('/', (req, res) => {{
  res.json({{
    name: '{}',
    version: '0.1.0',
    description: 'Express web API generated by Phoenix VCS'
  }});
}});

// 404 handler
app.use((req, res) => {{
  res.status(404).json({{ error: 'Not found' }});
}});

// Error handler
app.use((err, req, res, next) => {{
  console.error(err.stack);
  res.status(500).json({{ error: 'Internal server error' }});
}});

app.listen(PORT, () => {{
  console.log(`🔥 {} API server running on port ${{PORT}}`);
}});
"#, project_name.to_lowercase().replace(" ", "-"), project_name, project_name)
}

/// Generate .env.example for Express app
fn generate_env_example(_project_name: &str) -> String {
    r#"# Environment variables for Express app
# Copy this to .env and fill in your values

# Server
PORT=3000
NODE_ENV=development

# Database
DATABASE_URL=mongodb://localhost:27017/myapp

# Security
JWT_SECRET=your-secret-key-here
API_KEY=your-api-key-here

# External services
# Add your third-party API keys here
"#.to_string()
}
