// phoenix: iu_id = "litty-app"
// Generated by Phoenix VCS for litty

import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';

// Hero Component with "Hello World"
@customElement('hero-image')
export class HeroImage extends LitElement {
  static styles = css`
    :host {
      display: block;
      width: 100%;
    }
    .hero {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 80px 20px;
      text-align: center;
      border-radius: 12px;
      margin-bottom: 24px;
      box-shadow: 0 4px 20px rgba(0,0,0,0.15);
    }
    .hero h1 {
      font-size: 3.5rem;
      font-weight: bold;
      margin: 0;
      text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
      letter-spacing: 2px;
    }
    .hero p {
      font-size: 1.5rem;
      margin: 16px 0 0 0;
      opacity: 0.9;
    }
  `;

  render() {
    return html`
      <div class="hero">
        <h1>Hello World</h1>
        <p>Welcome to Litty</p>
      </div>
    `;
  }
}

// Simple Counter Component
@customElement('simple-counter')
export class SimpleCounter extends LitElement {
  static styles = css`
    :host {
      display: block;
      padding: 16px;
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
      margin-bottom: 16px;
    }
    .counter {
      display: flex;
      align-items: center;
      gap: 16px;
      font-size: 1.2rem;
    }
    button {
      padding: 8px 16px;
      font-size: 1rem;
      cursor: pointer;
      border: none;
      border-radius: 4px;
      background: #007bff;
      color: white;
    }
    button:hover {
      background: #0056b3;
    }
  `;

  @property({ type: Number }) count = 0;

  render() {
    return html`
      <div class="counter">
        <button @click=${() => this.count--}>-</button>
        <span>${this.count}</span>
        <button @click=${() => this.count++}>+</button>
      </div>
    `;
  }
}

// Main App Component
@customElement('litty-app')
export class littyApp extends LitElement {
  static styles = css`
    :host {
      display: block;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    h1 {
      color: #333;
      text-align: center;
    }
  `;

  render() {
    return html`
      <hero-image></hero-image>
      <simple-counter></simple-counter>
      <p>Lit Web Components app generated by Phoenix VCS</p>
    `;
  }
}

console.log('🔥 litty app loaded');
