// phoenix: iu_id = "litty-app"
// Generated by Phoenix VCS for litty

import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';

// Hero Component
@customElement('hero-image')
export class HeroImage extends LitElement {
  static styles = css`
    :host { display: block; width: 100%; }
    .hero {
      background: linear-gradient(135deg, #FFB6C1 0%, #E6E6FA 50%, #FFDAB9 100%);
      color: #4a4a4a; padding: 80px 20px; text-align: center;
      border-radius: 20px; margin-bottom: 24px;
      box-shadow: 0 8px 32px rgba(255,182,193,0.3);
      position: relative; overflow: hidden;
    }
    .hero::before { content: '🐾'; position: absolute; top: 20px; left: 20px; font-size: 2rem; opacity: 0.3; }
    .hero::after { content: '🐾'; position: absolute; bottom: 20px; right: 20px; font-size: 2rem; opacity: 0.3; transform: rotate(-20deg); }
    .hero h1 { font-size: 3.5rem; font-weight: bold; margin: 0; color: #6b5b95; }
    .hero p { font-size: 1.5rem; margin: 16px 0 0 0; opacity: 0.8; color: #8b7bb5; }
  `;
  render() {
    return html`<div class="hero"><h1>🐱 Welcome to litty! 🐱</h1><p>A purr-fect web components demo</p></div>`;
  }
}


// Counter Component - A purr-fectly reactive counter
@customElement('paw-counter')
export class PawCounter extends LitElement {
  @property({ type: Number }) count = 0;
  
  static styles = css`
    :host { display: block; }
    .counter-card {
      background: linear-gradient(145deg, #98FB98 0%, #FFDAB9 100%);
      border-radius: 20px;
      padding: 24px;
      text-align: center;
      box-shadow: 0 4px 16px rgba(152,251,152,0.3);
    }
    .count-display {
      font-size: 3rem;
      font-weight: bold;
      color: #6b5b95;
      margin: 16px 0;
    }
    .paw-button {
      background: white;
      border: none;
      border-radius: 50%;
      width: 48px;
      height: 48px;
      font-size: 1.5rem;
      cursor: pointer;
      margin: 0 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
      transition: transform 0.2s;
    }
    .paw-button:hover {
      transform: scale(1.1);
    }
    .paw-button:active {
      transform: scale(0.95);
    }
  `;
  
  render() {
    return html`
      <div class="counter-card">
        <div class="count-display">${this.count}</div>
        <button class="paw-button" @click=${() => this.count--}>🐾</button>
        <button class="paw-button" @click=${() => this.count++}>🐾</button>
      </div>
    `;
  }
}

// Todo List Component - A meow-velous task manager
@customElement('meow-todo')
export class MeowTodo extends LitElement {
  @property({ type: Array }) todos: { id: number; text: string; done: boolean }[] = [
    { id: 1, text: 'Pet the cat', done: false },
    { id: 2, text: 'Buy catnip', done: true },
    { id: 3, text: 'Build web components', done: false }
  ];
  @property({ type: String }) newTodo = '';
  
  static styles = css`
    :host { display: block; }
    .todo-card {
      background: linear-gradient(145deg, #E6E6FA 0%, #FFB6C1 100%);
      border-radius: 20px;
      padding: 24px;
      margin-top: 24px;
      box-shadow: 0 4px 16px rgba(230,230,250,0.4);
    }
    .todo-title {
      font-size: 1.5rem;
      color: #6b5b95;
      margin: 0 0 16px 0;
    }
    .todo-item {
      display: flex;
      align-items: center;
      padding: 12px;
      margin: 8px 0;
      background: white;
      border-radius: 12px;
      transition: transform 0.2s;
    }
    .todo-item:hover {
      transform: translateX(4px);
    }
    .todo-check {
      width: 24px;
      height: 24px;
      margin-right: 12px;
      cursor: pointer;
    }
    .todo-check:checked + span {
      text-decoration: line-through;
      opacity: 0.6;
    }
    .todo-text {
      flex: 1;
      color: #4a4a4a;
    }
    .add-todo {
      display: flex;
      gap: 8px;
      margin-top: 16px;
    }
    .todo-input {
      flex: 1;
      padding: 12px;
      border: none;
      border-radius: 12px;
      font-size: 1rem;
    }
    .add-button {
      background: white;
      border: none;
      border-radius: 12px;
      padding: 12px 20px;
      cursor: pointer;
      font-size: 1.2rem;
    }
  `;
  
  private addTodo() {
    if (this.newTodo.trim()) {
      this.todos = [...this.todos, {
        id: Date.now(),
        text: this.newTodo,
        done: false
      }];
      this.newTodo = '';
    }
  }
  
  private toggleTodo(id: number) {
    this.todos = this.todos.map(t => t.id === id ? { ...t, done: !t.done } : t);
  }
  
  private deleteTodo(id: number) {
    this.todos = this.todos.filter(t => t.id !== id);
  }
  
  render() {
    return html`
      <div class="todo-card">
        <h2 class="todo-title">📝 Meow-tasks</h2>
        ${this.todos.map(todo => html`
          <div class="todo-item">
            <input 
              class="todo-check" 
              type="checkbox" 
              .checked=${todo.done}
              @change=${() => this.toggleTodo(todo.id)}
            />
            <span class="todo-text">${todo.text}</span>
            <button @click=${() => this.deleteTodo(todo.id)}>🗑️</button>
          </div>
        `)}
        <div class="add-todo">
          <input 
            class="todo-input" 
            placeholder="Add a purr-fect task..."
            .value=${this.newTodo}
            @input=${(e: InputEvent) => this.newTodo = (e.target as HTMLInputElement).value}
            @keydown=${(e: KeyboardEvent) => e.key === 'Enter' && this.addTodo()}
          />
          <button class="add-button" @click=${this.addTodo}>➕</button>
        </div>
      </div>
    `;
  }
}

// Main App Component
@customElement('litty-app')
export class LittyApp extends LitElement {
  static styles = css`
    :host { display: block; max-width: 800px; margin: 0 auto; padding: 20px; }
  `;
  render() {
    return html`
      <hero-image></hero-image>
      <paw-counter></paw-counter>
      <meow-todo></meow-todo>
    `;
  }
}

console.log('🔥 litty app loaded with counter & todo list!');
