// phoenix: iu_id = "litty-app"
// Generated by Phoenix VCS for litty

import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';

// Hero Component
@customElement('hero-image')
export class HeroImage extends LitElement {
  static styles = css`
    :host {
      display: block;
      width: 100%;
    }
    .hero {
      background: linear-gradient(135deg, #FFB6C1 0%, #E6E6FA 50%, #FFDAB9 100%);
      color: #4a4a4a;
      padding: 80px 20px;
      text-align: center;
      border-radius: 20px;
      margin-bottom: 24px;
      box-shadow: 0 8px 32px rgba(255,182,193,0.3);
      position: relative;
      overflow: hidden;
    }
    .hero::before {
      content: '🐾';
      position: absolute;
      top: 20px;
      left: 20px;
      font-size: 2rem;
      opacity: 0.3;
    }
    .hero::after {
      content: '🐾';
      position: absolute;
      bottom: 20px;
      right: 20px;
      font-size: 2rem;
      opacity: 0.3;
      transform: rotate(-20deg);
    }
    .hero h1 {
      font-size: 3.5rem;
      font-weight: bold;
      margin: 0;
      text-shadow: 2px 2px 4px rgba(255,255,255,0.5);
      letter-spacing: 2px;
      color: #6b5b95;
    }
    .hero p {
      font-size: 1.5rem;
      margin: 16px 0 0 0;
      opacity: 0.8;
      color: #8b7bb5;
    }
  `;

  render() {
    return html`
      <div class="hero">
        <h1>🐱 Welcome to Litty! 🐱</h1>
        <p>A purr-fect web components demo</p>
      </div>
    `;
  }
}

// Simple Counter Component
@customElement('simple-counter')
export class SimpleCounter extends LitElement {
  static styles = css`
    :host {
      display: block;
      padding: 16px;
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
      margin-bottom: 16px;
    }
    .counter {
      display: flex;
      align-items: center;
      gap: 16px;
      font-size: 1.2rem;
    }
    button {
      padding: 8px 16px;
      font-size: 1rem;
      cursor: pointer;
      border: none;
      border-radius: 4px;
      background: #007bff;
      color: white;
    }
    button:hover {
      background: #0056b3;
    }
  `;$

  @property({ type: Number }) count = 0;

  render() {
    return html`
      <div class="counter">
        <button @click=${() => this.count--}>-</button>
        <span>${this.count}</span>
        <button @click=${() => this.count++}>+</button>
      </div>
    `;$
  }
}

// Todo List Component
@customElement('todo-list')
export class TodoList extends LitElement {
  static styles = css`
    :host {
      display: block;
      padding: 16px;
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
      margin-bottom: 16px;
    }
    .input-row {
      display: flex;
      gap: 8px;
      margin-bottom: 16px;
    }
    input {
      flex: 1;
      padding: 8px 12px;
      border: 1px solid #ddd;
      border-radius: 4px;
    }
    button {
      padding: 8px 16px;
      background: #28a745;
      color: white;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }
    button:hover {
      background: #218838;
    }
    ul {
      list-style: none;
      padding: 0;
      margin: 0;
    }
    li {
      display: flex;
      align-items: center;
      gap: 8px;
      padding: 8px 0;
      border-bottom: 1px solid #eee;
    }
    li:last-child {
      border-bottom: none;
    }
    input[type="checkbox"] {
      width: 20px;
      height: 20px;
    }
    .completed {
      text-decoration: line-through;
      color: #888;
    }
    .delete-btn {
      margin-left: auto;
      background: #dc3545;
      padding: 4px 12px;
      font-size: 0.875rem;
    }
  `;$

  @property({ type: Array }) todos = [];
  @property({ type: String }) newTodoText = '';

  render() {
    const remaining = this.todos.filter(t => !t.completed).length;
    
    return html`
      <h2>Todo List</h2>
      <div class="input-row">
        <input
          .value=${this.newTodoText}
          @input=${e => this.newTodoText = e.target.value}
          @keydown=${e => e.key === 'Enter' && this._addTodo()}
          placeholder="Add a new todo..."
        />
        <button @click=${this._addTodo}>Add</button>
      </div>
      <ul>
        ${this.todos.map(todo => html`
          <li>
            <input
              type="checkbox"
              .checked=${todo.completed}
              @change=${() => this._toggleTodo(todo.id)}
            />
            <span class=${todo.completed ? 'completed' : ''}>${todo.text}</span>
            <button class="delete-btn" @click=${() => this._deleteTodo(todo.id)}>Delete</button>
          </li>
        `)}
      </ul>
      <div>${remaining} of ${this.todos.length} remaining</div>
    `;$
  }

  _addTodo() {
    if (!this.newTodoText.trim()) return;
    this.todos = [...this.todos, {
      id: Date.now(),
      text: this.newTodoText.trim(),
      completed: false
    }];
    this.newTodoText = '';
  }

  _toggleTodo(id) {
    this.todos = this.todos.map(t =>
      t.id === id ? { ...t, completed: !t.completed } : t
    );
  }

  _deleteTodo(id) {
    this.todos = this.todos.filter(t => t.id !== id);
  }
}

// Main App Component
@customElement('litty-app')
export class LittyApp extends LitElement {
  static styles = css`
    :host {
      display: block;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
  `;$

  render() {
    return html`
      <hero-image></hero-image>
      <simple-counter></simple-counter>
      <todo-list></todo-list>
    `;$
  }
}
console.log('🔥 litty app loaded');
