// Python Generic Bundle - Expr-Based Code Generation (Layer 4)
//
// Uses the panproto Expr layer for runtime code generation:
//   Config ──► Expr Evaluation ──► Generated Code

use std::collections::HashMap;
use std::path::PathBuf;

/// Generate all files for the Python generic bundle using Expr-based generation
pub fn generate(_project_name: &str, spec_content: &str) -> HashMap<PathBuf, String> {
    use crate::pipeline::expr_bundle::{parse_spec_to_config, ExprBundleGenerator, ArtifactGenerator};
    
    // Parse spec into config
    let config = parse_spec_to_config(spec_content);
    
    // Build Expr-based generator
    ExprBundleGenerator::new("python-generic")
        .with_artifact("main.py", ArtifactGenerator::Expr(python_main_py))
        .with_artifact("pyproject.toml", ArtifactGenerator::Expr(python_pyproject_toml))
        .generate(&config)
}

fn python_main_py(config: &crate::pipeline::expr_bundle::BundleConfig) -> String {
    format!(r#"# phoenix: iu_id = "{}_main"
# Python application generated by Phoenix VCS

def main():
    """Main entry point for {}."""
    print(f"🔥 {} starting...")
    
    # TODO: Add your application logic here
    print("Hello from {}!")
    
    return 0

if __name__ == "__main__":
    exit(main())
"#, 
        config.project_name.replace("-", "_"),
        config.project_name,
        config.project_name,
        config.project_name
    )
}

fn python_pyproject_toml(config: &crate::pipeline::expr_bundle::BundleConfig) -> String {
    format!(r#"[project]
name = "{}"
version = "{}"
description = "{}"
requires-python = ">=3.10"
"#,
        config.project_name,
        config.version,
        config.project_description.as_deref().unwrap_or("Python application")
    )
}
