{
  description = "dataflow---stream-processing-pipeline - Generated by Phoenix VCS formal pipeline";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in
      {
        packages = {
          default = (pkgs.rustPlatform.buildRustPackage {
            pname = "dataflow---stream-processing-pipeline";
            version = "0.1.0";
            src = ./.;
            cargoLock.lockFile = ./Cargo.lock;
            meta.mainProgram = "dataflow---stream-processing-pipeline";
          });
        };
        devShells = {
          default = (pkgs.mkShell {
            buildInputs = with pkgs; [
              rust-bin.stable.latest.default
            ];
          });
        };
      }
    );
}