# Generated by Phoenix VCS
# Formal term morphism: IU → PythonTerm → Code

from textual.app import App, ComposeResult
from textual.containers import Vertical, Horizontal
from textual.widgets import Static

class HonoApiServerApp(App):
    """Generated from theory HonoAPIServer via ThPythonTextual"""

    CSS = """
    Screen {
        align: center middle;
        background: $surface;
    }
    """

    def compose(self) -> ComposeResult:
        # Theory: default compose
        yield Static("App", id="content")

    def on_mount(self) -> None:
        self.title = "HonoApiServer"


def main() -> int:
    # # Generated by Phoenix from theory: HonoAPIServer
    # # IU: hono-api-server
    app = HonoApiServerApp()
    app.run()
    return 0
