{
  description = "Hono API Server - Generated by Phoenix VCS formal pipeline";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in
      {
        devShells = {
          default = (pkgs.mkShell {
            buildInputs = with pkgs; [
              bun
              nodejs
            ];
          });
        };
        apps = {
          default = {
            type = "app";
            program = "bun run index.ts";
          };
        };
      }
    );
}