// phoenix: iu_id = "hono-server"
// Generated by Phoenix VCS for hono-api-server

import { Hono } from 'hono';
import { logger } from 'hono/logger';
import { cors } from 'hono/cors';
import type { Context } from 'hono';

// Types
interface HealthResponse {
  status: string;
  timestamp: string;
  service: string;
}

// Initialize Hono app
const app = new Hono();

// Middleware
app.use(logger());
app.use(cors({
  origin: '*',
  allowMethods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
  allowHeaders: ['Content-Type', 'Authorization'],
}));

// Health check
app.get('/health', (c: Context) => {
  const response: HealthResponse = {
    status: 'ok',
    timestamp: new Date().toISOString(),
    service: 'hono-api-server',
  };
  return c.json(response, 200);
});

// Root endpoint
app.get('/', (c: Context) => {
  return c.json({
    message: 'hono-api-server API',
    version: '0.1.0',
    docs: '/health',
  }, 200);
});

// API Routes
// Users API
app.get('/api/users', async (c: Context) => {
  const limit = c.req.query('limit') ? parseInt(c.req.query('limit')!) : 10;
  const offset = c.req.query('offset') ? parseInt(c.req.query('offset')!) : 0;
  return c.json({
    users: [],
    total: 0,
    limit,
    offset,
  }, 200);
});

app.get('/api/users/:id', async (c: Context) => {
  const id = c.req.param('id');
  return c.json({
    id,
    name: 'Sample User',
    email: 'user@example.com',
  }, 200);
});

app.post('/api/users', async (c: Context) => {
  const body = await c.req.json();
  return c.json({
    id: crypto.randomUUID(),
    created: true,
    ...body,
  }, 201);
});

app.put('/api/users/:id', async (c: Context) => {
  const id = c.req.param('id');
  const body = await c.req.json();
  return c.json({
    id,
    updated: true,
    ...body,
  }, 200);
});

app.delete('/api/users/:id', async (c: Context) => {
  const id = c.req.param('id');
  return c.body(null, 204);
});

// Items API
app.get('/api/items', async (c: Context) => {
  const limit = c.req.query('limit') ? parseInt(c.req.query('limit')!) : 10;
  const offset = c.req.query('offset') ? parseInt(c.req.query('offset')!) : 0;
  return c.json({
    items: [],
    total: 0,
    limit,
    offset,
  }, 200);
});

app.get('/api/items/:id', async (c: Context) => {
  const id = c.req.param('id');
  return c.json({
    id,
    name: 'Sample Item',
    price: 29.99,
  }, 200);
});

app.post('/api/items', async (c: Context) => {
  const body = await c.req.json();
  return c.json({
    id: crypto.randomUUID(),
    created: true,
    ...body,
  }, 201);
});

// Error handling
app.onError((err: Error, c: Context) => {
  console.error('Error:', err);
  return c.json({
    error: 'Internal Server Error',
    message: err.message,
  }, 500);
});

// 404 handler
app.notFound((c: Context) => {
  return c.json({ error: 'Not Found' }, 404);
});

// Export for Bun/Node
export default app;

// Bun serve (comment out for Node/Deno)
if (typeof Bun !== 'undefined') {
  Bun.serve({
    fetch: app.fetch,
    port: process.env.PORT ? parseInt(process.env.PORT) : 3000,
    hostname: process.env.HOST || '0.0.0.0',
  });
  console.log(`🚀 Server running at http://localhost:${process.env.PORT || 3000}`);
}
