// TypeScript Hono Bundle - Expr-Based Code Generation (Layer 4)
//
// Uses the panproto Expr layer for runtime code generation:
//   Config ──► Expr Evaluation ──► Generated Code

use std::collections::HashMap;
use std::path::PathBuf;

/// Generate all files for the TypeScript Hono bundle using Expr-based generation
pub fn generate(_project_name: &str, spec_content: &str) -> HashMap<PathBuf, String> {
    use crate::pipeline::expr_bundle::{parse_spec_to_config, ExprBundleGenerator, ArtifactGenerator};
    
    // Parse spec into config
    let config = parse_spec_to_config(spec_content);
    
    // Build Expr-based generator
    ExprBundleGenerator::new("ts-hono")
        .with_artifact("package.json", ArtifactGenerator::Expr(hono_package_json))
        .with_artifact("tsconfig.json", ArtifactGenerator::Static(hono_tsconfig().to_string()))
        .with_artifact("src/index.ts", ArtifactGenerator::Expr(hono_index_ts))
        .generate(&config)
}

fn hono_package_json(config: &crate::pipeline::expr_bundle::BundleConfig) -> String {
    format!(r#"{{
  "name": "{}",
  "version": "{}",
  "description": "{}",
  "type": "module",
  "scripts": {{
    "dev": "tsx watch src/index.ts",
    "build": "tsc",
    "start": "node dist/index.js"
  }},
  "dependencies": {{
    "hono": "^3.11.0"
  }},
  "devDependencies": {{
    "@types/node": "^20.0.0",
    "tsx": "^4.0.0",
    "typescript": "^5.3.0"
  }}
}}"#,
        config.project_name.to_lowercase().replace(" ", "-").replace("_", "-"),
        config.version,
        config.project_description.as_deref().unwrap_or("Hono web API")
    )
}

fn hono_tsconfig() -> &'static str {
    r#"{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "lib": ["ES2022"],
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "outDir": "./dist",
    "rootDir": "./src",
    "declaration": true
  },
  "include": ["src/**/*"]
}"#
}

fn hono_index_ts(config: &crate::pipeline::expr_bundle::BundleConfig) -> String {
    format!(r#"// phoenix: iu_id = "{}-api"
// Hono web API generated by Phoenix VCS

import {{ Hono }} from 'hono';

const app = new Hono();

// Health check
app.get('/health', (c) => {{
  return c.json({{ 
    status: 'ok', 
    timestamp: new Date().toISOString(),
    service: '{}'
  }});
}});

// Root
app.get('/', (c) => {{
  return c.json({{
    name: '{}',
    version: '{}',
    description: '{}'
  }});
}});

const port = parseInt(process.env.PORT || '3000');
console.log(`🔥 {} API server running on port ${{port}}`);

export default {{
  port,
  fetch: app.fetch,
}};
"#,
        config.project_name.to_lowercase().replace(" ", "-"),
        config.project_name,
        config.project_name,
        config.version,
        config.project_description.as_deref().unwrap_or("Hono web API"),
        config.project_name
    )
}
