// TypeScript Hono Bundle - Native Rust Code Generation
// This file is loaded by the Phoenix VCS pipeline for isolated bundles

use std::collections::HashMap;
use std::path::PathBuf;

/// Generate all files for the TypeScript Hono bundle
pub fn generate(project_name: &str, _spec_content: &str) -> HashMap<PathBuf, String> {
    let mut files = HashMap::new();
    
    files.insert(PathBuf::from("package.json"), generate_package_json(project_name));
    files.insert(PathBuf::from("tsconfig.json"), generate_tsconfig());
    files.insert(PathBuf::from("src/index.ts"), generate_index_ts(project_name));
    
    files
}

/// Generate package.json for Hono app
fn generate_package_json(project_name: &str) -> String {
    let sanitized = project_name.to_lowercase().replace(" ", "-").replace("_", "-");
    format!(r#"{{
  "name": "{}",
  "version": "0.1.0",
  "description": "Hono web API generated by Phoenix VCS",
  "type": "module",
  "scripts": {{
    "dev": "tsx watch src/index.ts",
    "build": "tsc",
    "start": "node dist/index.js"
  }},
  "dependencies": {{
    "hono": "^3.11.0"
  }},
  "devDependencies": {{
    "@types/node": "^20.0.0",
    "tsx": "^4.0.0",
    "typescript": "^5.3.0"
  }},
  "engines": {{
    "node": ">=18.0.0"
  }}
}}"#, sanitized)
}

/// Generate tsconfig.json for Hono app
fn generate_tsconfig() -> String {
    r#"{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "lib": ["ES2022"],
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "outDir": "./dist",
    "rootDir": "./src",
    "resolveJsonModule": true,
    "declaration": true,
    "declarationMap": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}"#.to_string()
}

/// Generate src/index.ts for Hono app
fn generate_index_ts(project_name: &str) -> String {
    format!(r#"// phoenix: iu_id = "{}-api"
// Hono web API generated by Phoenix VCS

import {{ Hono }} from 'hono';

const app = new Hono();

// Health check endpoint
app.get('/health', (c) => {{
  return c.json({{ 
    status: 'ok', 
    timestamp: new Date().toISOString(),
    service: '{}'
  }});
}});

// Root endpoint
app.get('/', (c) => {{
  return c.json({{
    name: '{}',
    version: '0.1.0',
    description: 'Hono web API generated by Phoenix VCS'
  }});
}});

// 404 handler
app.notFound((c) => {{
  return c.json({{ error: 'Not found' }}, 404);
}});

// Error handler
app.onError((err, c) => {{
  console.error('Error:', err);
  return c.json({{ error: 'Internal server error' }}, 500);
}});

// Start server
const port = parseInt(process.env.PORT || '3000');
console.log(`🔥 {} API server running on port ${{port}}`);

export default {{
  port,
  fetch: app.fetch,
}};
"#, project_name.to_lowercase().replace(" ", "-"), project_name, project_name, project_name)
}
