// TypeScript/Hono code generation
// μ_ts: ThSpec → ThTypeScript → String

use super::types::{BundleFile, FormalTheory, TemplateBundle};

/// Generate package.json using ThPackageJson formal theory
/// 
/// This implements μ_package_json: ThSpec → ThPackageJson → String
pub fn generate_package_json_term(project_name: &str, deps: &[String]) -> String {
    let sanitized_name = project_name.to_lowercase().replace(" ", "-").replace("_", "-");
    
    // Build dependencies object
    let dependencies = if deps.is_empty() {
        "  \"dependencies\": {}".to_string()
    } else {
        let dep_lines: Vec<String> = deps.iter()
            .map(|d| format!("    \"{}\": \"^latest\"", d))
            .collect();
        format!("  \"dependencies\": {{\n{}\n  }}", dep_lines.join(",\n"))
    };
    
    format!(r#"{{
  "name": "{}",
  "version": "0.1.0",
  "description": "Generated by Phoenix VCS formal pipeline",
  "type": "module",
  "scripts": {{
    "dev": "bun run --hot index.ts",
    "start": "bun run index.ts",
    "build": "bun build index.ts --outdir ./dist",
    "typecheck": "tsc --noEmit"
  }},
{},
  "devDependencies": {{
    "@types/bun": "latest",
    "typescript": "^5.3.0"
  }}
}}"#, sanitized_name, dependencies)
}

/// Generate tsconfig.json using ThTsConfig formal theory
/// 
/// This implements μ_tsconfig: ThTsConfig → String
pub fn generate_tsconfig_term() -> String {
    r#"{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "declaration": true,
    "outDir": "./dist",
    "rootDir": ".",
    "resolveJsonModule": true,
    "types": ["bun"]
  },
  "include": ["*.ts", "src/**/*.ts"],
  "exclude": ["node_modules", "dist"]
}"#.to_string()
}

/// Generate TypeScript Hono server code
/// 
/// This implements μ_ts: ThSpec → ThTypeScript → String
pub fn generate_hono_server_term(project_name: &str, _spec_content: &str) -> String {
    let sanitized_name = project_name.to_lowercase().replace(" ", "-").replace("_", "-");
    
    // Generate basic route handlers for Users and Items CRUD
    let route_code = generate_default_routes();
    
    format!(r#"// phoenix: iu_id = "hono-server"
// Generated by Phoenix VCS for {}

import {{ Hono }} from 'hono';
import {{ logger }} from 'hono/logger';
import {{ cors }} from 'hono/cors';
import type {{ Context }} from 'hono';

// Types
interface HealthResponse {{
  status: string;
  timestamp: string;
  service: string;
}}

// Initialize Hono app
const app = new Hono();

// Middleware
app.use(logger());
app.use(cors({{
  origin: '*',
  allowMethods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
  allowHeaders: ['Content-Type', 'Authorization'],
}}));

// Health check
app.get('/health', (c: Context) => {{
  const response: HealthResponse = {{
    status: 'ok',
    timestamp: new Date().toISOString(),
    service: '{}',
  }};
  return c.json(response, 200);
}});

// Root endpoint
app.get('/', (c: Context) => {{
  return c.json({{
    message: '{} API',
    version: '0.1.0',
    docs: '/health',
  }}, 200);
}});

// API Routes
{}

// Error handling
app.onError((err: Error, c: Context) => {{
  console.error('Error:', err);
  return c.json({{
    error: 'Internal Server Error',
    message: err.message,
  }}, 500);
}});

// 404 handler
app.notFound((c: Context) => {{
  return c.json({{ error: 'Not Found' }}, 404);
}});

// Export for Bun/Node
export default app;

// Bun serve (comment out for Node/Deno)
if (typeof Bun !== 'undefined') {{
  Bun.serve({{
    fetch: app.fetch,
    port: process.env.PORT ? parseInt(process.env.PORT) : 3000,
    hostname: process.env.HOST || '0.0.0.0',
  }});
  console.log(`🚀 Server running at http://localhost:${{process.env.PORT || 3000}}`);
}}
"#, sanitized_name, sanitized_name, sanitized_name, route_code)
}

fn generate_default_routes() -> String {
    r#"// Users API
app.get('/api/users', async (c: Context) => {
  const limit = c.req.query('limit') ? parseInt(c.req.query('limit')!) : 10;
  const offset = c.req.query('offset') ? parseInt(c.req.query('offset')!) : 0;
  return c.json({
    users: [],
    total: 0,
    limit,
    offset,
  }, 200);
});

app.get('/api/users/:id', async (c: Context) => {
  const id = c.req.param('id');
  return c.json({
    id,
    name: 'Sample User',
    email: 'user@example.com',
  }, 200);
});

app.post('/api/users', async (c: Context) => {
  const body = await c.req.json();
  return c.json({
    id: crypto.randomUUID(),
    created: true,
    ...body,
  }, 201);
});

app.put('/api/users/:id', async (c: Context) => {
  const id = c.req.param('id');
  const body = await c.req.json();
  return c.json({
    id,
    updated: true,
    ...body,
  }, 200);
});

app.delete('/api/users/:id', async (c: Context) => {
  const id = c.req.param('id');
  return c.body(null, 204);
});

// Items API
app.get('/api/items', async (c: Context) => {
  const limit = c.req.query('limit') ? parseInt(c.req.query('limit')!) : 10;
  const offset = c.req.query('offset') ? parseInt(c.req.query('offset')!) : 0;
  return c.json({
    items: [],
    total: 0,
    limit,
    offset,
  }, 200);
});

app.get('/api/items/:id', async (c: Context) => {
  const id = c.req.param('id');
  return c.json({
    id,
    name: 'Sample Item',
    price: 29.99,
  }, 200);
});

app.post('/api/items', async (c: Context) => {
  const body = await c.req.json();
  return c.json({
    id: crypto.randomUUID(),
    created: true,
    ...body,
  }, 201);
});"#.to_string()
}

/// Build the ts-hono bundle definition
pub fn ts_hono_bundle() -> TemplateBundle {
    TemplateBundle {
        name: "ts-hono".to_string(),
        files: vec![
            BundleFile {
                path: std::path::PathBuf::from("flake.nix"),
                theory: FormalTheory::ThNix,
                description: "Nix flake with Bun/Node.js toolchain".to_string(),
            },
            BundleFile {
                path: std::path::PathBuf::from("package.json"),
                theory: FormalTheory::ThPackageJson,
                description: "Node.js package configuration".to_string(),
            },
            BundleFile {
                path: std::path::PathBuf::from("tsconfig.json"),
                theory: FormalTheory::ThTsConfig,
                description: "TypeScript configuration".to_string(),
            },
            BundleFile {
                path: std::path::PathBuf::from("README.md"),
                theory: FormalTheory::ThMarkdown,
                description: "Project documentation".to_string(),
            },
            BundleFile {
                path: std::path::PathBuf::from("index.ts"),
                theory: FormalTheory::ThTypeScript,
                description: "Hono server entry point".to_string(),
            },
        ],
        base_deps: vec![
            "hono".to_string(),
        ],
    }
}

/// Generate TypeScript-specific files
pub fn generate_typescript_file(
    theory: &FormalTheory,
    project_name: &str,
    _spec_content: &str,
    _ius: &[crate::pipeline::ImplementationUnit],
    _all_deps: &[String],
) -> String {
    match theory {
        FormalTheory::ThTypeScript => {
            generate_hono_server_term(project_name, "")
        }
        FormalTheory::ThPackageJson => {
            generate_package_json_term(project_name, &["hono".to_string()])
        }
        FormalTheory::ThTsConfig => {
            generate_tsconfig_term()
        }
        _ => "// Unknown TypeScript theory".to_string(),
    }
}
