// TypeScript/Hono code generation
// μ_ts: ThSpec → ThTypeScript → String

use super::types::{BundleFile, FormalTheory, TemplateBundle};

/// Generate package.json using ThPackageJson formal theory
/// 
/// This implements μ_package_json: ThSpec → ThPackageJson → String
pub fn generate_package_json_term(project_name: &str, deps: &[String]) -> String {
    let sanitized_name = project_name.to_lowercase().replace(" ", "-").replace("_", "-");
    
    // Build dependencies object
    let dependencies = if deps.is_empty() {
        "  \"dependencies\": {}".to_string()
    } else {
        let dep_lines: Vec<String> = deps.iter()
            .map(|d| format!("    \"{}\": \"^latest\"", d))
            .collect();
        format!("  \"dependencies\": {{\n{}\n  }}", dep_lines.join(",\n"))
    };
    
    format!(r#"{{
  "name": "{}",
  "version": "0.1.0",
  "description": "Generated by Phoenix VCS formal pipeline",
  "type": "module",
  "scripts": {{
    "dev": "bun run --hot index.ts",
    "start": "bun run index.ts",
    "build": "bun build index.ts --outdir ./dist",
    "typecheck": "tsc --noEmit"
  }},
{},
  "devDependencies": {{
    "@types/bun": "latest",
    "typescript": "^5.3.0"
  }}
}}"#, sanitized_name, dependencies)
}

/// Generate tsconfig.json using ThTsConfig formal theory
/// 
/// This implements μ_tsconfig: ThTsConfig → String
pub fn generate_tsconfig_term() -> String {
    r#"{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "declaration": true,
    "outDir": "./dist",
    "rootDir": ".",
    "resolveJsonModule": true,
    "types": ["bun"]
  },
  "include": ["*.ts", "src/**/*.ts"],
  "exclude": ["node_modules", "dist"]
}"#.to_string()
}

/// Generate TypeScript Hono server code
/// 
/// This implements μ_ts: ThSpec → ThTypeScript → String
pub fn generate_hono_server_term(project_name: &str, _spec_content: &str) -> String {
    let sanitized_name = project_name.to_lowercase().replace(" ", "-").replace("_", "-");
    
    // Generate basic route handlers for Users and Items CRUD
    let route_code = generate_default_routes();
    
    format!(r#"// phoenix: iu_id = "hono-server"
// Generated by Phoenix VCS for {}

import {{ Hono }} from 'hono';
import {{ logger }} from 'hono/logger';
import {{ cors }} from 'hono/cors';
import type {{ Context }} from 'hono';

// Types
interface HealthResponse {{
  status: string;
  timestamp: string;
  service: string;
}}

// Initialize Hono app
const app = new Hono();

// Middleware
app.use(logger());
app.use(cors({{
  origin: '*',
  allowMethods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
  allowHeaders: ['Content-Type', 'Authorization'],
}}));

// Health check
app.get('/health', (c: Context) => {{
  const response: HealthResponse = {{
    status: 'ok',
    timestamp: new Date().toISOString(),
    service: '{}',
  }};
  return c.json(response, 200);
}});

// Root endpoint
app.get('/', (c: Context) => {{
  return c.json({{
    message: '{} API',
    version: '0.1.0',
    docs: '/health',
  }}, 200);
}});

// API Routes
{}

// Error handling
app.onError((err: Error, c: Context) => {{
  console.error('Error:', err);
  return c.json({{
    error: 'Internal Server Error',
    message: err.message,
  }}, 500);
}});

// 404 handler
app.notFound((c: Context) => {{
  return c.json({{ error: 'Not Found' }}, 404);
}});

// Export for Bun/Node
export default app;

// Bun serve (comment out for Node/Deno)
if (typeof Bun !== 'undefined') {{
  Bun.serve({{
    fetch: app.fetch,
    port: process.env.PORT ? parseInt(process.env.PORT) : 3000,
    hostname: process.env.HOST || '0.0.0.0',
  }});
  console.log(`🚀 Server running at http://localhost:${{process.env.PORT || 3000}}`);
}}
"#, sanitized_name, sanitized_name, sanitized_name, route_code)
}

fn generate_default_routes() -> String {
    r#"// Users API
app.get('/api/users', async (c: Context) => {
  const limit = c.req.query('limit') ? parseInt(c.req.query('limit')!) : 10;
  const offset = c.req.query('offset') ? parseInt(c.req.query('offset')!) : 0;
  return c.json({
    users: [],
    total: 0,
    limit,
    offset,
  }, 200);
});

app.get('/api/users/:id', async (c: Context) => {
  const id = c.req.param('id');
  return c.json({
    id,
    name: 'Sample User',
    email: 'user@example.com',
  }, 200);
});

app.post('/api/users', async (c: Context) => {
  const body = await c.req.json();
  return c.json({
    id: crypto.randomUUID(),
    created: true,
    ...body,
  }, 201);
});

app.put('/api/users/:id', async (c: Context) => {
  const id = c.req.param('id');
  const body = await c.req.json();
  return c.json({
    id,
    updated: true,
    ...body,
  }, 200);
});

app.delete('/api/users/:id', async (c: Context) => {
  const id = c.req.param('id');
  return c.body(null, 204);
});

// Items API
app.get('/api/items', async (c: Context) => {
  const limit = c.req.query('limit') ? parseInt(c.req.query('limit')!) : 10;
  const offset = c.req.query('offset') ? parseInt(c.req.query('offset')!) : 0;
  return c.json({
    items: [],
    total: 0,
    limit,
    offset,
  }, 200);
});

app.get('/api/items/:id', async (c: Context) => {
  const id = c.req.param('id');
  return c.json({
    id,
    name: 'Sample Item',
    price: 29.99,
  }, 200);
});

app.post('/api/items', async (c: Context) => {
  const body = await c.req.json();
  return c.json({
    id: crypto.randomUUID(),
    created: true,
    ...body,
  }, 201);
});"#.to_string()
}

/// Build the ts-hono bundle definition
pub fn ts_hono_bundle() -> TemplateBundle {
    TemplateBundle {
        name: "ts-hono".to_string(),
        files: vec![
            BundleFile {
                path: std::path::PathBuf::from("flake.nix"),
                theory: FormalTheory::ThNix,
                description: "Nix flake with Bun/Node.js toolchain".to_string(),
            },
            BundleFile {
                path: std::path::PathBuf::from("package.json"),
                theory: FormalTheory::ThPackageJson,
                description: "Node.js package configuration".to_string(),
            },
            BundleFile {
                path: std::path::PathBuf::from("tsconfig.json"),
                theory: FormalTheory::ThTsConfig,
                description: "TypeScript configuration".to_string(),
            },
            BundleFile {
                path: std::path::PathBuf::from("README.md"),
                theory: FormalTheory::ThMarkdown,
                description: "Project documentation".to_string(),
            },
            BundleFile {
                path: std::path::PathBuf::from("index.ts"),
                theory: FormalTheory::ThTypeScript,
                description: "Hono server entry point".to_string(),
            },
        ],
        base_deps: vec![
            "hono".to_string(),
        ],
    }
}

/// Generate Lit package.json with Vite
/// 
/// This implements μ_package_json: ThSpec → ThPackageJson → String (Lit variant)
pub fn generate_lit_package_json_term(project_name: &str) -> String {
    let sanitized_name = project_name.to_lowercase().replace(" ", "-").replace("_", "-");
    
    format!(r#"{{
  "name": "{}",
  "version": "0.1.0",
  "description": "Lit Web Components app generated by Phoenix VCS",
  "type": "module",
  "scripts": {{
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  }},
  "dependencies": {{
    "lit": "^3.0.0"
  }},
  "devDependencies": {{
    "typescript": "^5.2.0",
    "vite": "^5.0.0"
  }}
}}"#, sanitized_name)
}

/// Generate Lit tsconfig.json with decorators
/// 
/// This implements μ_tsconfig: ThTsConfig → String (Lit variant)
pub fn generate_lit_tsconfig_term() -> String {
    r#"{{
  "compilerOptions": {{
    "target": "ES2020",
    "module": "ESNext",
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "moduleResolution": "bundler",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "experimentalDecorators": true,
    "useDefineForClassFields": false,
    "outDir": "./dist",
    "rootDir": "./src"
  }},
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}}"#.to_string()
}

/// Generate Vite config for Lit
/// 
/// This implements μ_vite_config: ThSpec → String
pub fn generate_lit_vite_config_term() -> String {
    r#"import {{ defineConfig }} from 'vite';

export default defineConfig({{
  server: {{
    port: 3000,
    open: true
  }},
  build: {{
    outDir: 'dist',
    sourcemap: true
  }}
}});
"#.to_string()
}

/// Generate HTML entry point for Lit app
/// 
/// This implements μ_html: ThSpec → String
pub fn generate_lit_index_html_term(project_name: &str) -> String {
    format!(r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{} - Lit App</title>
  <script type="module" src="/src/main.ts"></script>
  <style>
    body {{
      margin: 0;
      padding: 20px;
      font-family: system-ui, -apple-system, sans-serif;
      background: #f5f5f5;
    }}
  </style>
</head>
<body>
  <{}-app></{}-app>
</body>
</html>
"#, project_name, 
    project_name.to_lowercase().replace(" ", "-"),
    project_name.to_lowercase().replace(" ", "-"))
}

/// Generate Lit main.ts with example components
/// 
/// This implements μ_ts: ThSpec → ThTypeScript → String (Lit variant)
pub fn generate_lit_main_term(project_name: &str) -> String {
    let tag_name = project_name.to_lowercase().replace(" ", "-").replace("_", "-");
    
    format!(r#"// phoenix: iu_id = "{}-app"
// Generated by Phoenix VCS for {}

import {{ LitElement, html, css }} from 'lit';
import {{ customElement, property }} from 'lit/decorators.js';

// Simple Counter Component
@customElement('simple-counter')
export class SimpleCounter extends LitElement {{
  static styles = css`
    :host {{
      display: block;
      padding: 16px;
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
      margin-bottom: 16px;
    }}
    .counter {{
      display: flex;
      align-items: center;
      gap: 16px;
      font-size: 1.2rem;
    }}
    button {{
      padding: 8px 16px;
      font-size: 1rem;
      cursor: pointer;
      border: none;
      border-radius: 4px;
      background: #007bff;
      color: white;
    }}
    button:hover {{
      background: #0056b3;
    }}
  `;

  @property({{ type: Number }}) count = 0;

  render() {{
    return html`
      <div class="counter">
        <button @click=${{() => this.count--}}>-</button>
        <span>${{this.count}}</span>
        <button @click=${{() => this.count++}}>+</button>
      </div>
    `;
  }}
}}

// Main App Component
@customElement('{}-app')
export class {}App extends LitElement {{
  static styles = css`
    :host {{
      display: block;
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
    }}
    h1 {{
      color: #333;
      text-align: center;
    }}
  `;

  render() {{
    return html`
      <h1>🔥 {}</h1>
      <simple-counter></simple-counter>
      <p>Lit Web Components app generated by Phoenix VCS</p>
    `;
  }}
}}

console.log('🔥 {} app loaded');
"#, tag_name, project_name, tag_name, tag_name, project_name.replace("-", " ").replace("_", " ").to_uppercase(), project_name)
}

/// Generate TypeScript-specific files
/// Generate Lit-specific files
pub fn generate_lit_file(
    theory: &FormalTheory,
    project_name: &str,
) -> String {
    match theory {
        FormalTheory::ThLitPackageJson => {
            generate_lit_package_json_term(project_name)
        }
        FormalTheory::ThLitTsConfig => {
            generate_lit_tsconfig_term()
        }
        FormalTheory::ThLitViteConfig => {
            generate_lit_vite_config_term()
        }
        FormalTheory::ThLitHtml => {
            generate_lit_index_html_term(project_name)
        }
        FormalTheory::ThLitMain => {
            generate_lit_main_term(project_name)
        }
        _ => "// Unknown Lit theory".to_string(),
    }
}

/// Generate TypeScript-specific files (Hono or generic)
pub fn generate_typescript_file(
    theory: &FormalTheory,
    project_name: &str,
    _spec_content: &str,
    _ius: &[crate::pipeline::ImplementationUnit],
    _all_deps: &[String],
) -> String {
    match theory {
        FormalTheory::ThTypeScript => {
            generate_hono_server_term(project_name, "")
        }
        FormalTheory::ThPackageJson => {
            generate_package_json_term(project_name, &["hono".to_string()])
        }
        FormalTheory::ThTsConfig => {
            generate_tsconfig_term()
        }
        // Lit theories
        FormalTheory::ThLitPackageJson => {
            generate_lit_package_json_term(project_name)
        }
        FormalTheory::ThLitTsConfig => {
            generate_lit_tsconfig_term()
        }
        FormalTheory::ThLitViteConfig => {
            generate_lit_vite_config_term()
        }
        FormalTheory::ThLitHtml => {
            generate_lit_index_html_term(project_name)
        }
        FormalTheory::ThLitMain => {
            generate_lit_main_term(project_name)
        }
        _ => "// Unknown TypeScript theory".to_string(),
    }
}
