/**
 * Minimal Phoenix Regen - Direct LLM, no complexity.
 */

import type { ImplementationUnit } from './models/iu.js';
import type { CanonicalNode } from './models/canonical.js';
import type { IUManifest, RegenMetadata, FileManifestEntry } from './models/manifest.js';
import type { PiSDKProvider } from './llm/pi-sdk.js';
import { buildPrompt, getSystemPrompt } from './llm/prompt.js';
import type { ResolvedTarget } from './models/architecture.js';
import { sha256 } from './semhash.js';

const TOOLCHAIN_VERSION = 'phoenix-minimal/0.3.0';

export interface RegenResult {
  iu_id: string;
  files: Map<string, string>;
  manifest: IUManifest;
}

export interface RegenContext {
  llm?: PiSDKProvider;
  canonNodes?: CanonicalNode[];
  allIUs?: ImplementationUnit[];
  projectRoot?: string;
  target?: ResolvedTarget | null;
  verbose?: boolean;
  log?: (msg: string) => void;
}

/**
 * Generate ONE IU. One output file. Direct LLM. Fast.
 */
export async function generateIU(iu: ImplementationUnit, ctx?: RegenContext): Promise<RegenResult> {
  const log = ctx?.verbose && ctx?.log ? ctx.log : () => {};
  const modelId = ctx?.llm ? `${ctx.llm.name}/${ctx.llm.model}` : 'stub';

  log(`[${iu.name}] Generating...`);

  const files = new Map<string, string>();

  // Generate each output file sequentially
  for (const outputPath of iu.output_files) {
    let content: string;

    if (ctx?.llm && ctx.canonNodes) {
      content = await generateWithLLM(iu, ctx.llm, ctx.canonNodes, ctx);
    } else {
      content = generateStub(iu);
    }

    files.set(outputPath, content);
    log(`[${iu.name}] ${outputPath}: ${content.length} chars`);
  }

  // Build manifest
  const fileEntries: Record<string, FileManifestEntry> = {};
  for (const [path, content] of files) {
    fileEntries[path] = { path, content_hash: sha256(content), size: content.length };
  }

  const metadata: RegenMetadata = {
    model_id: modelId,
    promptpack_hash: sha256(JSON.stringify(iu.contract)),
    toolchain_version: TOOLCHAIN_VERSION,
    generated_at: new Date().toISOString(),
  };

  return {
    iu_id: iu.iu_id,
    files,
    manifest: {
      iu_id: iu.iu_id,
      iu_name: iu.name,
      files: fileEntries,
      regen_metadata: metadata,
    },
  };
}

/**
 * Direct LLM generation - ONE call, no retries, no typecheck.
 */
async function generateWithLLM(
  iu: ImplementationUnit,
  llm: PiSDKProvider,
  canonNodes: CanonicalNode[],
  ctx?: RegenContext
): Promise<string> {
  const log = ctx?.verbose && ctx?.log ? ctx.log : () => {};
  const startTime = Date.now();

  // Find sibling modules
  const iuDir = iu.output_files[0]?.split('/').slice(0, -1).join('/');
  const siblings = ctx?.allIUs
    ?.filter(o => o.iu_id !== iu.iu_id && o.output_files[0]?.startsWith(iuDir || ''))
    .map(o => o.name) ?? [];

  // Build prompt
  const prompt = buildPrompt(iu, canonNodes, siblings, ctx?.target);
  const systemPrompt = getSystemPrompt(ctx?.target);

  log(`  [${iu.name}] Prompt: ${prompt.length} chars`);

  // SINGLE LLM CALL
  const raw = await llm.generate(
    prompt,
    { system: systemPrompt, temperature: 0.2, maxTokens: 8192 },
    (chunk: string) => {} // No streaming logging for speed
  );

  log(`  [${iu.name}] LLM: ${raw.length} chars in ${Date.now() - startTime}ms`);

  // Simple clean - extract from markdown if present
  return cleanCode(raw);
}

/**
 * Simple code cleaner - just extract from markdown blocks.
 */
function cleanCode(raw: string): string {
  const trimmed = raw.trim();

  // If wrapped in ```typescript, extract it
  const match = trimmed.match(/```(?:typescript|ts)?\s*\n?([\s\S]*?)\n?```/);
  if (match) return match[1].trim();

  // Otherwise return as-is
  return trimmed;
}

/**
 * Simple stub when no LLM available.
 */
function generateStub(iu: ImplementationUnit): string {
  return `// ${iu.name} - Generated by Phoenix
// ${iu.contract.description}

export default {};

export const _phoenix = {
  iu_id: '${iu.iu_id}',
  name: '${iu.name}',
  risk_tier: '${iu.risk_tier}',
  canon_ids: [${iu.source_canon_ids.join(', ')} as const],
} as const;`;
}

/**
 * Generate multiple IUs sequentially.
 */
export async function generateAll(ius: ImplementationUnit[], ctx?: RegenContext): Promise<RegenResult[]> {
  const results: RegenResult[] = [];
  for (const iu of ius) {
    results.push(await generateIU(iu, ctx));
  }
  return results;
}
