//! Example: Using Phoenix VCS Rust Client
//!
//! This example demonstrates the core concepts of Phoenix VCS:
//! - Content-addressed identity
//! - Drift detection
//! - Evidence & policy
//! - Cascade computation
//! - Shadow pipeline

use std::collections::HashMap;

fn main() -> anyhow::Result<()> {
    println!("=== Phoenix VCS Rust Client Demo ===\n");
    
    // ============================================
    // 1. Content-Addressed Identity
    // ============================================
    println!("1. Content-Addressed Identity");
    println!("   ──────────────────────────");
    
    let requirement_text = "System shall validate email format";
    let normalized = phoenix_vcs::normalize_text(requirement_text);
    let canon_id = phoenix_vcs::canon_id(&normalized);
    
    println!("   Input: '{}'", requirement_text);
    println!("   Normalized: '{}'", normalized);
    println!("   Canon ID: {}", canon_id);
    println!("   Short: {}...\n", phoenix_vcs::short_hash(&canon_id));
    
    // IU ID generation
    let name = "AuthModule";
    let contract = "Handles user authentication and session management";
    let source_canons = vec![canon_id.clone()];
    let iu_id = phoenix_vcs::iu_id(name, contract, &source_canons);
    
    println!("   IU '{}' with contract:", name);
    println!("   '{}'", contract);
    println!("   IU ID: {}", iu_id);
    println!("   Short: {}...\n", phoenix_vcs::short_hash(&iu_id));
    
    // ============================================
    // 2. Drift Detection
    // ============================================
    println!("2. Drift Detection");
    println!("   ─────────────────");
    
    // Create a mock manifest
    let mut files = HashMap::new();
    files.insert(
        "src/auth.rs".to_string(),
        phoenix_vcs::drift::FileEntry {
            iu_id: iu_id.clone(),
            hash: phoenix_vcs::file_hash("// Generated by Phoenix"),
            size: 23,
            generated_at: chrono::Utc::now().to_rfc3339(),
        },
    );
    
    let manifest = phoenix_vcs::drift::GeneratedManifest {
        version: "1.0.0".to_string(),
        generated_at: chrono::Utc::now().to_rfc3339(),
        files,
    };
    
    println!("   Manifest version: {}", manifest.version);
    println!("   Files tracked: {}\n", manifest.files.len());
    
    // ============================================
    // 3. Evidence & Policy
    // ============================================
    println!("3. Evidence & Policy");
    println!("   ──────────────────");
    
    let risk_tiers = vec![
        phoenix_vcs::evidence::RiskTier::Low,
        phoenix_vcs::evidence::RiskTier::Medium,
        phoenix_vcs::evidence::RiskTier::High,
        phoenix_vcs::evidence::RiskTier::Critical,
    ];
    
    for tier in &risk_tiers {
        let required = phoenix_vcs::evidence::get_required_evidence(*tier);
        println!("   {:?} risk requires {} items:", tier, required.len());
        for (i, kind) in required.iter().enumerate() {
            println!("      {}. {}", i + 1, kind);
        }
        println!();
    }
    
    // Create evidence and evaluate
    let evidence = vec![
        phoenix_vcs::evidence::EvidenceRecord {
            kind: phoenix_vcs::evidence::EvidenceKind::Typecheck,
            status: phoenix_vcs::evidence::EvidenceStatus::Passed,
            timestamp: chrono::Utc::now().to_rfc3339(),
            iu_id: iu_id.clone(),
            details: Some("No type errors".to_string()),
            duration_ms: Some(150),
            signed_by: None,
            signature_hash: None,
            proof_system: None,
            test_count: None,
            pass_count: None,
            fail_count: None,
        },
        phoenix_vcs::evidence::EvidenceRecord {
            kind: phoenix_vcs::evidence::EvidenceKind::Lint,
            status: phoenix_vcs::evidence::EvidenceStatus::Passed,
            timestamp: chrono::Utc::now().to_rfc3339(),
            iu_id: iu_id.clone(),
            details: Some("No lint errors".to_string()),
            duration_ms: Some(80),
            signed_by: None,
            signature_hash: None,
            proof_system: None,
            test_count: None,
            pass_count: None,
            fail_count: None,
        },
    ];
    
    let eval = phoenix_vcs::evidence::evaluate_policy(
        &iu_id,
        phoenix_vcs::evidence::RiskTier::Low,
        &evidence,
    );
    
    println!("   Policy evaluation for {}...:", phoenix_vcs::short_hash(&iu_id));
    println!("   Status: {:?}", eval.status);
    println!("   Score: {}/100", eval.score);
    println!("   Missing evidence: {} items\n", eval.missing_evidence.len());
    
    // ============================================
    // 4. Dependency Graph & Cascade
    // ============================================
    println!("4. Dependency Graph & Cascade");
    println!("   ──────────────────────────");
    
    let ius = vec![
        phoenix_vcs::cascade::IUDef {
            iu_id: "iu-database".to_string(),
            dependencies: None,
            risk_tier: phoenix_vcs::cascade::RiskTier::Critical,
            output_files: vec!["database.rs".to_string()],
            source_canon_ids: Some(vec!["canon-db".to_string()]),
        },
        phoenix_vcs::cascade::IUDef {
            iu_id: "iu-auth".to_string(),
            dependencies: Some(vec!["iu-database".to_string()]),
            risk_tier: phoenix_vcs::cascade::RiskTier::High,
            output_files: vec!["auth.rs".to_string()],
            source_canon_ids: Some(vec!["canon-auth".to_string()]),
        },
        phoenix_vcs::cascade::IUDef {
            iu_id: "iu-api".to_string(),
            dependencies: Some(vec!["iu-auth".to_string()]),
            risk_tier: phoenix_vcs::cascade::RiskTier::Medium,
            output_files: vec!["api.rs".to_string()],
            source_canon_ids: Some(vec!["canon-api".to_string()]),
        },
    ];
    
    let graph = phoenix_vcs::cascade::build_dependency_graph(&ius);
    println!("   Built graph with {} nodes and {} edges", graph.nodes.len(), graph.edges.len());
    
    // Compute cascade for a failure
    let cascade = phoenix_vcs::cascade::compute_cascade(
        &graph,
        "iu-database",
        "unit_tests",
        "Database connection timeout",
    );
    
    println!("\n   Cascade from 'iu-database' failure:");
    println!("   Source: {}...", phoenix_vcs::short_hash(&cascade.source_iu));
    println!("   Failure: {}", cascade.source_failure);
    println!("   Affected IUs: {}", cascade.affected_ius.len());
    println!("   Actions generated: {}", cascade.actions.len());
    
    // Group actions by type
    let mut action_counts: HashMap<String, usize> = HashMap::new();
    for action in &cascade.actions {
        let type_name = match action {
            phoenix_vcs::cascade::CascadeAction::Retypecheck { .. } => "RETYPECHECK",
            phoenix_vcs::cascade::CascadeAction::ReboundaryCheck { .. } => "REBOUNDARY_CHECK",
            phoenix_vcs::cascade::CascadeAction::Retest { .. } => "RETEST",
            phoenix_vcs::cascade::CascadeAction::Regenerate { .. } => "REGENERATE",
            phoenix_vcs::cascade::CascadeAction::Block { .. } => "BLOCK",
        };
        *action_counts.entry(type_name.to_string()).or_insert(0) += 1;
    }
    
    println!("\n   Action breakdown:");
    for (action_type, count) in &action_counts {
        println!("      {}: {}", action_type, count);
    }
    
    // ============================================
    // 5. Selective Invalidation
    // ============================================
    println!("\n5. Selective Invalidation");
    println!("   ──────────────────────");
    
    let mut iu_to_canon_map = HashMap::new();
    iu_to_canon_map.insert("iu-database".to_string(), vec!["canon-db".to_string()]);
    iu_to_canon_map.insert("iu-auth".to_string(), vec!["canon-auth".to_string()]);
    iu_to_canon_map.insert("iu-api".to_string(), vec!["canon-api".to_string()]);
    
    let changed_canons = vec!["canon-db".to_string()];
    let invalidated = phoenix_vcs::cascade::compute_invalidation(
        &graph,
        &changed_canons,
        &iu_to_canon_map,
    );
    
    println!("   Changed requirements: 1 (canon-db)");
    println!("   Invalidated IUs: {}", invalidated.len());
    for iu_id in &invalidated {
        println!("      - {}", phoenix_vcs::short_hash(iu_id));
    }
    println!("   Selective rate: Only affected subtree invalidated\n");
    
    // ============================================
    // 6. D-Rate Tracking
    // ============================================
    println!("6. D-Rate Tracking");
    println!("   ────────────────");
    
    let mut tracker = phoenix_vcs::DRateTracker::new(100);
    
    // Simulate classification results
    for i in 0..100 {
        let class = match i % 10 {
            0 => phoenix_vcs::identity::ChangeClass::D,  // 10% D-rate
            1..=3 => phoenix_vcs::identity::ChangeClass::C,
            4..=6 => phoenix_vcs::identity::ChangeClass::B,
            _ => phoenix_vcs::identity::ChangeClass::A,
        };
        tracker.record(class);
    }
    
    let d_rate_status = tracker.get_status();
    println!("   Window size: 100 classifications");
    println!("   D-rate: {:.1}%", d_rate_status.d_rate * 100.0);
    println!("   Level: {:?}", d_rate_status.level);
    println!("   Message: {}\n", d_rate_status.message);
    
    // ============================================
    // 7. Shadow Pipeline
    // ============================================
    println!("7. Shadow Pipeline");
    println!("   ────────────────");
    
    use phoenix_vcs::identity::{CanonNode, CanonNodeType};
    
    let old_nodes = vec![
        CanonNode {
            id: "req-1".to_string(),
            node_type: CanonNodeType::Requirement,
            text: "System shall validate user input".to_string(),
            confidence: 0.9,
            edges: vec![],
        },
        CanonNode {
            id: "req-2".to_string(),
            node_type: CanonNodeType::Requirement,
            text: "System shall encrypt passwords".to_string(),
            confidence: 0.95,
            edges: vec![],
        },
    ];
    
    let new_nodes = vec![
        CanonNode {
            id: "req-1".to_string(),
            node_type: CanonNodeType::Requirement,
            text: "System shall validate user input".to_string(),
            confidence: 0.9,
            edges: vec![],
        },
        CanonNode {
            id: "req-2".to_string(),
            node_type: CanonNodeType::Requirement,
            text: "System shall encrypt passwords".to_string(),
            confidence: 0.95,
            edges: vec![],
        },
        CanonNode {
            id: "req-3".to_string(),
            node_type: CanonNodeType::Requirement,
            text: "System shall log access attempts".to_string(),
            confidence: 0.85,
            edges: vec![],
        },
    ];
    
    let shadow_result = phoenix_vcs::shadow::run_shadow_pipeline(
        old_nodes,
        new_nodes,
        "v1.0.0",
        "v1.1.0",
    );
    
    println!("   Old pipeline: {}...", phoenix_vcs::short_hash(&shadow_result.old_pipeline_id));
    println!("   New pipeline: {}...", phoenix_vcs::short_hash(&shadow_result.new_pipeline_id));
    println!("   Classification: {:?}", shadow_result.classification);
    println!("   Metrics:");
    println!("      Node change: {:.1}%", shadow_result.metrics.node_change_pct);
    println!("      Orphan nodes: {}", shadow_result.metrics.orphan_nodes);
    println!("      Risk escalations: {}", shadow_result.metrics.risk_escalations);
    
    match shadow_result.classification {
        phoenix_vcs::shadow::UpgradeClassification::Safe => {
            println!("\n   ✅ SAFE to upgrade");
        }
        phoenix_vcs::shadow::UpgradeClassification::CompactionEvent => {
            println!("\n   ⚠️  COMPACTION EVENT - review required");
        }
        phoenix_vcs::shadow::UpgradeClassification::Reject => {
            println!("\n   ❌ REJECT - breaking changes detected");
        }
    }
    
    println!("\n=== Demo Complete ===");
    Ok(())
}
