#!/usr/bin/env bash
# Phoenix Issue Reporter Script
# Usage: ./phoenix-issue.sh
# Asks for issue description, then dispatches pi agent to fix it

set -e

# Colors for output
BOLD='\033[1m'
BLUE='\033[34m'
GREEN='\033[32m'
YELLOW='\033[33m'
RED='\033[31m'
RESET='\033[0m'

echo ""
echo -e "${BOLD}${BLUE}╔════════════════════════════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}${BLUE}║        🔥 PHOENIX VCS - Issue Reporting & Fix Pipeline         ║${RESET}"
echo -e "${BOLD}${BLUE}╚════════════════════════════════════════════════════════════════╝${RESET}"
echo ""

# Get the project directory
PROJECT_DIR="/home/nandi/code/freeq/freeq-py"
cd "$PROJECT_DIR"

echo -e "${BOLD}Project:${RESET} $PROJECT_DIR"
echo ""

# Ask for issue description
echo -e "${BOLD}${YELLOW}Describe the issue you're experiencing:${RESET}"
echo "  (e.g., 'auth screen not showing', 'UI is blank after login', 'sidebar not populated')"
echo ""
read -r -p "> " ISSUE_DESCRIPTION

echo ""
echo -e "${BOLD}Confirming issue:${RESET} $ISSUE_DESCRIPTION"
echo ""

# Build the prompt for the agent
PROMPT=$(cat <<EOF
PHOENIX MORPHISM PIPELINE FIX REQUEST

Issue Description:
$ISSUE_DESCRIPTION

Project: /home/nandi/code/freeq/freeq-py

YOUR TASK:
1. Read the spec files in /home/nandi/code/freeq/freeq-py/spec/ to understand current requirements
2. Identify which spec needs updating to address the issue
3. Update the appropriate spec file with new REQUIREMENT clauses
4. Run the Phoenix morphism pipeline: node /home/nandi/code/phoenix/.pi/skills/phoenix-pipeline/pipeline.js .
5. The pipeline will execute: μ_ingest → μ_canon → μ_plan → μ_codegen
6. Report back the morphism chain results
7. If the issue requires code changes not generated by the pipeline, explain what manual edits are needed

FOLLOW THE SPEC-DRIVEN WORKFLOW:
- Fix the spec first
- Run the pipeline
- Let the morphisms generate code
- Report completion

DO NOT manually edit generated code unless explicitly required by the spec.
EOF
)

echo -e "${BOLD}${GREEN}Dispatching Phoenix agent to fix the issue...${RESET}"
echo ""

# Run pi agent in dispatch mode
# Note: Already in PROJECT_DIR from cd command above
pi "$PROMPT"

echo ""
echo -e "${BOLD}${GREEN}✅ Agent dispatched!${RESET}"
echo ""
echo -e "${BOLD}The Phoenix morphism pipeline is now processing your issue.${RESET}"
echo "  - μ_ingest: Extracting clauses from updated spec"
echo "  - μ_canon: Canonicalizing requirements"  
echo "  - μ_plan: Planning Implementation Units"
echo "  - μ_codegen: Generating code from IUs"
echo ""
echo -e "Check ${YELLOW}.phoenix/state.json${RESET} for pipeline status."
echo ""
