import { describe, it, expect } from 'vitest';
import { generateIU, generateAll } from '../../src/regen.js';
import { planIUs } from '../../src/iu-planner.js';
import { parseSpec } from '../../src/spec-parser.js';
import { extractCanonicalNodes } from '../../src/canonicalizer.js';

describe('generateIU', () => {
  function makeIU() {
    const clauses = parseSpec('# Auth\n\nUsers must authenticate with email.', 'test.md');
    const canon = extractCanonicalNodes(clauses);
    return planIUs(canon, clauses)[0];
  }

  it('generates files for an IU', () => {
    const iu = makeIU();
    const result = generateIU(iu);
    expect(result.files.size).toBeGreaterThan(0);
  });

  it('generated code contains IU metadata', () => {
    const iu = makeIU();
    const result = generateIU(iu);
    const content = [...result.files.values()][0];
    expect(content).toContain('AUTO-GENERATED by Phoenix VCS');
    expect(content).toContain(iu.iu_id);
    expect(content).toContain(iu.risk_tier);
  });

  it('generated code contains a function stub', () => {
    const iu = makeIU();
    const result = generateIU(iu);
    const content = [...result.files.values()][0];
    expect(content).toContain('export function');
    expect(content).toContain('throw new Error');
  });

  it('produces a manifest with correct file hashes', () => {
    const iu = makeIU();
    const result = generateIU(iu);
    expect(result.manifest.iu_id).toBe(iu.iu_id);

    for (const [path, entry] of Object.entries(result.manifest.files)) {
      expect(entry.content_hash).toHaveLength(64);
      expect(entry.size).toBeGreaterThan(0);
      expect(result.files.has(path)).toBe(true);
    }
  });

  it('records regen metadata', () => {
    const iu = makeIU();
    const result = generateIU(iu);
    const meta = result.manifest.regen_metadata;
    expect(meta.model_id).toBeTruthy();
    expect(meta.toolchain_version).toBeTruthy();
    expect(meta.promptpack_hash).toHaveLength(64);
    expect(meta.generated_at).toBeTruthy();
  });
});

describe('generateAll', () => {
  it('generates for multiple IUs', () => {
    const spec = `# Auth\n\nUsers must authenticate.\n\n# Billing\n\nPayments must be processed.`;
    const clauses = parseSpec(spec, 'test.md');
    const canon = extractCanonicalNodes(clauses);
    const ius = planIUs(canon, clauses);
    const results = generateAll(ius);
    expect(results.length).toBe(ius.length);
  });
});
