{
  description = "express-demo-api - Generated by Phoenix VCS formal pipeline";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in
      {
        packages = {
          default = (pkgs.python312Packages.buildPythonApplication {
            pname = "express-demo-api";
            version = "0.1.0";
            src = ./.;
            format = "pyproject";
            build-system = with pkgs.python312Packages; [ hatchling ];
            propagatedBuildInputs = with pkgs.python312Packages; [ textual express mongoose cors helmet morgan dotenv ];
            meta.mainProgram = "express-demo-api";
          });
        };
        devShells = {
          default = (pkgs.mkShell {
            buildInputs = with pkgs; [
              python312
              python312Packages.textual
              python312Packages.express
              python312Packages.mongoose
              python312Packages.cors
              python312Packages.helmet
              python312Packages.morgan
              python312Packages.dotenv
            ];
          });
        };
      }
    );
}