// Lit Bundle - Native Rust Code Generation
// This file is loaded by the Phoenix VCS pipeline for NCL-native bundles

use std::collections::HashMap;
use std::path::PathBuf;

/// Generate all files for the Lit bundle
pub fn generate(project_name: &str, spec_content: &str) -> HashMap<PathBuf, String> {
    let mut files = HashMap::new();
    
    files.insert(PathBuf::from("package.json"), generate_package_json(project_name));
    files.insert(PathBuf::from("tsconfig.json"), generate_tsconfig());
    files.insert(PathBuf::from("vite.config.ts"), generate_vite_config());
    files.insert(PathBuf::from("index.html"), generate_index_html(project_name));
    files.insert(PathBuf::from("src/main.ts"), generate_main(project_name, spec_content));
    
    files
}

/// Generate package.json
fn generate_package_json(project_name: &str) -> String {
    let sanitized = project_name.to_lowercase().replace(" ", "-").replace("_", "-");
    format!(r#"{{
  "name": "{}",
  "version": "0.1.0",
  "description": "Lit Web Components app generated by Phoenix VCS",
  "type": "module",
  "scripts": {{
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  }},
  "dependencies": {{
    "lit": "^3.0.0"
  }},
  "devDependencies": {{
    "typescript": "^5.2.0",
    "vite": "^5.0.0"
  }}
}}"#, sanitized)
}

/// Generate tsconfig.json
fn generate_tsconfig() -> String {
    r#"{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ESNext",
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "moduleResolution": "bundler",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "experimentalDecorators": true,
    "useDefineForClassFields": false,
    "outDir": "./dist",
    "rootDir": "./src"
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}"#.to_string()
}

/// Generate vite.config.ts
fn generate_vite_config() -> String {
    r#"import { defineConfig } from 'vite';

export default defineConfig({
  server: {
    port: 3000,
    open: true
  },
  build: {
    outDir: 'dist',
    sourcemap: true
  }
});
"#.to_string()
}

/// Generate index.html
fn generate_index_html(project_name: &str) -> String {
    let tag = project_name.to_lowercase().replace(" ", "-").replace("_", "-");
    format!(r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{} - Lit App</title>
  <script type="module" src="/src/main.ts"></script>
  <style>
    body {{
      margin: 0;
      padding: 20px;
      font-family: system-ui, -apple-system, sans-serif;
      background: #f5f5f5;
    }}
  </style>
</head>
<body>
  <{}-app></{}-app>
</body>
</html>
"#, project_name, tag, tag)
}

/// Generate src/main.ts with configurable components
fn generate_main(project_name: &str, spec_content: &str) -> String {
    let tag = project_name.to_lowercase().replace(" ", "-").replace("_", "-");
    let class_name = to_pascal_case(&tag);
    
    // Parse spec for component configuration
    let config = parse_spec_config(spec_content);
    
    let mut main_ts = String::new();
    
    // Header
    main_ts.push_str(&format!("// phoenix: iu_id = \"{}-app\"\n", tag));
    main_ts.push_str(&format!("// Generated by Phoenix VCS for {}\n\n", project_name));
    main_ts.push_str("import { LitElement, html, css } from 'lit';\n");
    main_ts.push_str("import { customElement, property } from 'lit/decorators.js';\n\n");
    
    // Hero component (if enabled)
    if config.has_hero {
        main_ts.push_str(&generate_hero_component(&config.hero_message, &config.hero_subtitle));
        main_ts.push_str("\n");
    }
    
    // Counter component
    if config.has_counter {
        main_ts.push_str(&generate_counter_component());
        main_ts.push_str("\n");
    }
    
    // Todo list component
    if config.has_todo {
        main_ts.push_str(&generate_todo_component());
        main_ts.push_str("\n");
    }
    
    // Main app component
    main_ts.push_str(&generate_app_component(&tag, &class_name, &config));
    main_ts.push_str("\n");
    main_ts.push_str(&format!("console.log('🔥 {} app loaded');\n", project_name));
    
    main_ts
}

/// Configuration parsed from spec
struct ComponentConfig {
    has_hero: bool,
    hero_message: String,
    hero_subtitle: String,
    has_counter: bool,
    has_todo: bool,
}

impl Default for ComponentConfig {
    fn default() -> Self {
        Self {
            has_hero: true,
            hero_message: "Hello World".to_string(),
            hero_subtitle: "Welcome".to_string(),
            has_counter: true,
            has_todo: false,
        }
    }
}

/// Parse component configuration from spec content
fn parse_spec_config(spec_content: &str) -> ComponentConfig {
    let mut config = ComponentConfig::default();
    let content_lower = spec_content.to_lowercase();
    
    // Check for hero
    config.has_hero = content_lower.contains("hero");
    
    // Check for counter
    config.has_counter = content_lower.contains("counter");
    
    // Check for todo
    config.has_todo = content_lower.contains("todo");
    
    // Try to extract hero message
    if let Some(msg) = extract_hero_message(spec_content) {
        config.hero_message = msg;
    }
    
    config
}

/// Extract hero message from spec
fn extract_hero_message(spec_content: &str) -> Option<String> {
    // Look for patterns like "message = \"Hello World\"" or similar
    for line in spec_content.lines() {
        let line_lower = line.to_lowercase();
        if line_lower.contains("hero") && line_lower.contains("message") {
            // Try to extract quoted string
            if let Some(start) = line.find('"') {
                let rest = &line[start + 1..];
                if let Some(end) = rest.find('"') {
                    return Some(rest[..end].to_string());
                }
            }
        }
    }
    None
}

/// Convert kebab-case to PascalCase
fn to_pascal_case(s: &str) -> String {
    s.split('-')
        .map(|p| {
            let mut chars = p.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + &chars.as_str().to_lowercase(),
            }
        })
        .collect()
}

/// Generate hero component
fn generate_hero_component(message: &str, subtitle: &str) -> String {
    format!(r#"// Hero Component
@customElement('hero-image')
export class HeroImage extends LitElement {{
  static styles = css\`
    :host {{
      display: block;
      width: 100%;
    }}
    .hero {{
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 80px 20px;
      text-align: center;
      border-radius: 12px;
      margin-bottom: 24px;
      box-shadow: 0 4px 20px rgba(0,0,0,0.15);
    }}
    .hero h1 {{
      font-size: 3.5rem;
      font-weight: bold;
      margin: 0;
      text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
      letter-spacing: 2px;
    }}
    .hero p {{
      font-size: 1.5rem;
      margin: 16px 0 0 0;
      opacity: 0.9;
    }}
  \`;

  render() {{
    return html\`
      <div class="hero">
        <h1>{}</h1>
        <p>{}</p>
      </div>
    \`;
  }}
}}
"#, message, subtitle)
}

/// Generate counter component
fn generate_counter_component() -> String {
    r#"// Simple Counter Component
@customElement('simple-counter')
export class SimpleCounter extends LitElement {
  static styles = css\`
    :host {
      display: block;
      padding: 16px;
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
      margin-bottom: 16px;
    }
    .counter {
      display: flex;
      align-items: center;
      gap: 16px;
      font-size: 1.2rem;
    }
    button {
      padding: 8px 16px;
      font-size: 1rem;
      cursor: pointer;
      border: none;
      border-radius: 4px;
      background: #007bff;
      color: white;
    }
    button:hover {
      background: #0056b3;
    }
  \`;

  @property({ type: Number }) count = 0;

  render() {
    return html\`
      <div class="counter">
        <button @click=\${() => this.count--}>-</button>
        <span>\${this.count}</span>
        <button @click=\${() => this.count++}>+</button>
      </div>
    \`;
  }
}
"#.to_string()
}

/// Generate todo list component
fn generate_todo_component() -> String {
    r#"// Todo List Component
@customElement('todo-list')
export class TodoList extends LitElement {
  static styles = css\`
    :host {
      display: block;
      padding: 16px;
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
      margin-bottom: 16px;
    }
    .input-row {
      display: flex;
      gap: 8px;
      margin-bottom: 16px;
    }
    input {
      flex: 1;
      padding: 8px 12px;
      border: 1px solid #ddd;
      border-radius: 4px;
    }
    button {
      padding: 8px 16px;
      background: #28a745;
      color: white;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }
    button:hover {
      background: #218838;
    }
    ul {
      list-style: none;
      padding: 0;
      margin: 0;
    }
    li {
      display: flex;
      align-items: center;
      gap: 8px;
      padding: 8px 0;
      border-bottom: 1px solid #eee;
    }
    li:last-child {
      border-bottom: none;
    }
    input[type="checkbox"] {
      width: 20px;
      height: 20px;
    }
    .completed {
      text-decoration: line-through;
      color: #888;
    }
    .delete-btn {
      margin-left: auto;
      background: #dc3545;
      padding: 4px 12px;
      font-size: 0.875rem;
    }
  \`;

  @property({ type: Array }) todos = [];
  @property({ type: String }) newTodoText = '';

  render() {
    const remaining = this.todos.filter(t => !t.completed).length;
    
    return html\`
      <h2>Todo List</h2>
      <div class="input-row">
        <input
          .value=\${this.newTodoText}
          @input=\${e => this.newTodoText = e.target.value}
          @keydown=\${e => e.key === 'Enter' && this._addTodo()}
          placeholder="Add a new todo..."
        />
        <button @click=\${this._addTodo}>Add</button>
      </div>
      <ul>
        \${this.todos.map(todo => html\`
          <li>
            <input
              type="checkbox"
              .checked=\${todo.completed}
              @change=\${() => this._toggleTodo(todo.id)}
            />
            <span class=\${todo.completed ? 'completed' : ''}>\${todo.text}</span>
            <button class="delete-btn" @click=\${() => this._deleteTodo(todo.id)}>Delete</button>
          </li>
        \`)}
      </ul>
      <div>\${remaining} of \${this.todos.length} remaining</div>
    \`;
  }

  _addTodo() {
    if (!this.newTodoText.trim()) return;
    this.todos = [...this.todos, {
      id: Date.now(),
      text: this.newTodoText.trim(),
      completed: false
    }];
    this.newTodoText = '';
  }

  _toggleTodo(id) {
    this.todos = this.todos.map(t =>
      t.id === id ? { ...t, completed: !t.completed } : t
    );
  }

  _deleteTodo(id) {
    this.todos = this.todos.filter(t => t.id !== id);
  }
}
"#.to_string()
}

/// Generate main app component
fn generate_app_component(tag: &str, class_name: &str, config: &ComponentConfig) -> String {
    let mut component = String::new();
    
    component.push_str(&format!("// Main App Component\n@customElement('{}-app')\n", tag));
    component.push_str(&format!("export class {}App extends LitElement {{\n", class_name));
    component.push_str(r#"  static styles = css\`
    :host {
      display: block;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
  \`;

  render() {
    return html\`
"#);
    
    if config.has_hero {
        component.push_str("      <hero-image></hero-image>\n");
    }
    
    if config.has_counter {
        component.push_str("      <simple-counter></simple-counter>\n");
    }
    
    if config.has_todo {
        component.push_str("      <todo-list></todo-list>\n");
    }
    
    component.push_str(r#"    \`;
  }
}"#);
    
    component
}
