{
  description = "todo-list - Generated by Phoenix VCS formal pipeline";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in
      {
        packages = {
          default = (pkgs.python312Packages.buildPythonApplication {
            pname = "todo-list";
            version = "0.1.0";
            src = ./.;
            format = "pyproject";
            build-system = with pkgs.python312Packages; [ hatchling ];
            propagatedBuildInputs = with pkgs.python312Packages; [ textual lit typescript vite ];
            meta.mainProgram = "todo-list";
          });
        };
        devShells = {
          default = (pkgs.mkShell {
            buildInputs = with pkgs; [
              python312
              python312Packages.textual
              python312Packages.lit
              python312Packages.typescript
              python312Packages.vite
            ];
          });
        };
      }
    );
}